[hls]
relative_roots=C:/2EAI-HAC-2526-TaskHLS-bj-mk-tm/Edges
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=vitis_convolution/Read_Rows  
syn.directive.array_partition=vitis_convolution/vitis_convolution(unsigned char volatile*, char volatile*, char (*) [3])::local_input dim=1 type=cyclic factor=3 variable=vitis_convolution(unsigned char volatile*, char volatile*, char (*) [3])::local_input
syn.directive.loop_flatten=vitis_convolution/Conv_Rows  
syn.directive.loop_flatten=vitis_convolution/Write_Rows  


