[hls]
relative_roots=C:/2EAI-HAC-2526-TaskHLS-bj-mk-tm/Edges
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=vitis_convolution/Read_Rows  
syn.directive.loop_flatten=vitis_convolution/Write_Rows  


