-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vitis_convolution_vitis_convolution_Pipeline_Read_Rows_Read_Cols is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_in_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_in_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_in_0_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_in_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_in_0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_in_0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_in_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_in_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_in_0_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_in_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_in_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_in_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_in_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_in_0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_in_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_in_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem_in_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_in_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_in_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_in_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_in_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    input_img : IN STD_LOGIC_VECTOR (31 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0 : OUT STD_LOGIC;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of vitis_convolution_vitis_convolution_Pipeline_Read_Rows_Read_Cols is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv15_4000 : STD_LOGIC_VECTOR (14 downto 0) := "100000000000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv17_156 : STD_LOGIC_VECTOR (16 downto 0) := "00000000101010110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv8_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000011";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv11_2B : STD_LOGIC_VECTOR (10 downto 0) := "00000101011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln18_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_in_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal gmem_in_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln18_fu_297_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln18_reg_490 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln18_1_fu_305_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln18_1_reg_496 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln21_fu_313_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln21_reg_502 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln21_1_fu_317_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln21_1_reg_507 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal tmp_1_reg_517 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_1_reg_517_pp0_iter3_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal gmem_in_addr_reg_522 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_452_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln21_2_reg_533 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln21_2_reg_533_pp0_iter6_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln21_2_reg_533_pp0_iter7_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln21_2_reg_533_pp0_iter8_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln21_2_reg_533_pp0_iter9_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln21_2_reg_533_pp0_iter10_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln21_2_reg_533_pp0_iter11_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln21_2_reg_533_pp0_iter12_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln21_2_reg_533_pp0_iter13_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal gmem_in_addr_read_reg_538 : STD_LOGIC_VECTOR (7 downto 0);
    signal gmem_in_addr_read_reg_538_pp0_iter12_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal gmem_in_addr_read_reg_538_pp0_iter13_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln18_fu_423_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln18_reg_551 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln19_fu_427_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln19_reg_555 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln21_3_fu_440_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal add_ln21_1_fu_408_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_fu_90 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln19_fu_321_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal r_fu_94 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal indvar_flatten_fu_98 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal add_ln18_1_fu_268_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0_local : STD_LOGIC;
    signal p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0_local : STD_LOGIC;
    signal icmp_ln19_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln18_fu_285_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln18_fu_340_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln18_fu_340_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln18_fu_340_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_356_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_346_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln19_fu_368_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln19_fu_368_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln19_fu_368_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_384_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln_fu_389_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln21_fu_396_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln21_fu_403_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln21_1_fu_400_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_356_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_384_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_452_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_452_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_452_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_356_ce : STD_LOGIC;
    signal grp_fu_384_ce : STD_LOGIC;
    signal grp_fu_452_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_452_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_452_p20 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln18_fu_340_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln19_fu_368_p00 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component vitis_convolution_mul_8ns_10ns_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component vitis_convolution_urem_8ns_3ns_2_12_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component vitis_convolution_mac_muladd_7ns_6ns_7ns_11_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        din2 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component vitis_convolution_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_8ns_10ns_17_1_1_U1 : component vitis_convolution_mul_8ns_10ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln18_fu_340_p0,
        din1 => mul_ln18_fu_340_p1,
        dout => mul_ln18_fu_340_p2);

    urem_8ns_3ns_2_12_1_U2 : component vitis_convolution_urem_8ns_3ns_2_12_1
    generic map (
        ID => 1,
        NUM_STAGE => 12,
        din0_WIDTH => 8,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln18_1_reg_496,
        din1 => grp_fu_356_p1,
        ce => grp_fu_356_ce,
        dout => grp_fu_356_p2);

    mul_8ns_10ns_17_1_1_U3 : component vitis_convolution_mul_8ns_10ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln19_fu_368_p0,
        din1 => mul_ln19_fu_368_p1,
        dout => mul_ln19_fu_368_p2);

    urem_8ns_3ns_2_12_1_U4 : component vitis_convolution_urem_8ns_3ns_2_12_1
    generic map (
        ID => 1,
        NUM_STAGE => 12,
        din0_WIDTH => 8,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln18_reg_490,
        din1 => grp_fu_384_p1,
        ce => grp_fu_384_ce,
        dout => grp_fu_384_p2);

    mac_muladd_7ns_6ns_7ns_11_4_1_U5 : component vitis_convolution_mac_muladd_7ns_6ns_7ns_11_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 7,
        din1_WIDTH => 6,
        din2_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_452_p0,
        din1 => grp_fu_452_p1,
        din2 => grp_fu_452_p2,
        ce => grp_fu_452_ce,
        dout => grp_fu_452_p3);

    flow_control_loop_pipe_sequential_init_U : component vitis_convolution_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    c_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_90 <= ap_const_lv8_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    c_fu_90 <= add_ln19_fu_321_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln18_fu_262_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_98 <= add_ln18_1_fu_268_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_98 <= ap_const_lv15_0;
                end if;
            end if; 
        end if;
    end process;

    r_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    r_fu_94 <= ap_const_lv8_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    r_fu_94 <= select_ln18_1_fu_305_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                add_ln21_2_reg_533 <= grp_fu_452_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                add_ln21_2_reg_533_pp0_iter10_reg <= add_ln21_2_reg_533_pp0_iter9_reg;
                add_ln21_2_reg_533_pp0_iter11_reg <= add_ln21_2_reg_533_pp0_iter10_reg;
                add_ln21_2_reg_533_pp0_iter12_reg <= add_ln21_2_reg_533_pp0_iter11_reg;
                add_ln21_2_reg_533_pp0_iter13_reg <= add_ln21_2_reg_533_pp0_iter12_reg;
                add_ln21_2_reg_533_pp0_iter6_reg <= add_ln21_2_reg_533;
                add_ln21_2_reg_533_pp0_iter7_reg <= add_ln21_2_reg_533_pp0_iter6_reg;
                add_ln21_2_reg_533_pp0_iter8_reg <= add_ln21_2_reg_533_pp0_iter7_reg;
                add_ln21_2_reg_533_pp0_iter9_reg <= add_ln21_2_reg_533_pp0_iter8_reg;
                tmp_1_reg_517 <= mul_ln19_fu_368_p2(16 downto 10);
                tmp_1_reg_517_pp0_iter3_reg <= tmp_1_reg_517;
                trunc_ln18_reg_551 <= trunc_ln18_fu_423_p1;
                trunc_ln19_reg_555 <= trunc_ln19_fu_427_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                gmem_in_addr_read_reg_538 <= m_axi_gmem_in_0_RDATA;
                gmem_in_addr_read_reg_538_pp0_iter12_reg <= gmem_in_addr_read_reg_538;
                gmem_in_addr_read_reg_538_pp0_iter13_reg <= gmem_in_addr_read_reg_538_pp0_iter12_reg;
                gmem_in_addr_reg_522 <= add_ln21_1_fu_408_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                select_ln18_1_reg_496 <= select_ln18_1_fu_305_p3;
                select_ln18_reg_490 <= select_ln18_fu_297_p3;
                trunc_ln21_1_reg_507 <= trunc_ln21_1_fu_317_p1;
                trunc_ln21_reg_502 <= trunc_ln21_fu_313_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln18_1_fu_268_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv15_1));
    add_ln18_fu_285_p2 <= std_logic_vector(unsigned(r_fu_94) + unsigned(ap_const_lv8_1));
    add_ln19_fu_321_p2 <= std_logic_vector(unsigned(select_ln18_fu_297_p3) + unsigned(ap_const_lv8_1));
    add_ln21_1_fu_408_p2 <= std_logic_vector(unsigned(add_ln21_fu_403_p2) + unsigned(zext_ln21_1_fu_400_p1));
    add_ln21_fu_403_p2 <= std_logic_vector(unsigned(zext_ln21_fu_396_p1) + unsigned(input_img));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter11, m_axi_gmem_in_0_ARREADY, m_axi_gmem_in_0_RVALID)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (m_axi_gmem_in_0_RVALID = ap_const_logic_0)) or ((m_axi_gmem_in_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter11, m_axi_gmem_in_0_ARREADY, m_axi_gmem_in_0_RVALID)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (m_axi_gmem_in_0_RVALID = ap_const_logic_0)) or ((m_axi_gmem_in_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter11, m_axi_gmem_in_0_ARREADY, m_axi_gmem_in_0_RVALID)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (m_axi_gmem_in_0_RVALID = ap_const_logic_0)) or ((m_axi_gmem_in_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln18_fu_262_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln18_fu_262_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten_fu_98, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv15_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_98;
        end if; 
    end process;


    gmem_in_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem_in_0_ARREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem_in_blk_n_AR <= m_axi_gmem_in_0_ARREADY;
        else 
            gmem_in_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_in_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter11, m_axi_gmem_in_0_RVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            gmem_in_blk_n_R <= m_axi_gmem_in_0_RVALID;
        else 
            gmem_in_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_356_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            grp_fu_356_ce <= ap_const_logic_1;
        else 
            grp_fu_356_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_356_p1 <= ap_const_lv8_3(3 - 1 downto 0);

    grp_fu_384_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            grp_fu_384_ce <= ap_const_logic_1;
        else 
            grp_fu_384_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_384_p1 <= ap_const_lv8_3(3 - 1 downto 0);

    grp_fu_452_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            grp_fu_452_ce <= ap_const_logic_1;
        else 
            grp_fu_452_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_452_p0 <= grp_fu_452_p00(7 - 1 downto 0);
    grp_fu_452_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_346_p4),11));
    grp_fu_452_p1 <= ap_const_lv11_2B(6 - 1 downto 0);
    grp_fu_452_p2 <= grp_fu_452_p20(7 - 1 downto 0);
    grp_fu_452_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_reg_517_pp0_iter3_reg),11));
    icmp_ln18_fu_262_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv15_4000) else "0";
    icmp_ln19_fu_291_p2 <= "1" when (c_fu_90 = ap_const_lv8_80) else "0";
    m_axi_gmem_in_0_ARADDR <= gmem_in_addr_reg_522;
    m_axi_gmem_in_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_in_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_in_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_in_0_ARLEN <= ap_const_lv32_1;
    m_axi_gmem_in_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_in_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_in_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_in_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_in_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_in_0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem_in_0_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem_in_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_in_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_in_0_AWADDR <= ap_const_lv32_0;
    m_axi_gmem_in_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_in_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_in_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_in_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_in_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_in_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_in_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_in_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_in_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_in_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_in_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_in_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_in_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_gmem_in_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_in_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_in_0_WDATA <= ap_const_lv8_0;
    m_axi_gmem_in_0_WID <= ap_const_lv1_0;
    m_axi_gmem_in_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_in_0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem_in_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_in_0_WVALID <= ap_const_logic_0;
    mul_ln18_fu_340_p0 <= mul_ln18_fu_340_p00(8 - 1 downto 0);
    mul_ln18_fu_340_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln18_1_reg_496),17));
    mul_ln18_fu_340_p1 <= ap_const_lv17_156(10 - 1 downto 0);
    mul_ln19_fu_368_p0 <= mul_ln19_fu_368_p00(8 - 1 downto 0);
    mul_ln19_fu_368_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln18_reg_490),17));
    mul_ln19_fu_368_p1 <= ap_const_lv17_156(10 - 1 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_address0 <= zext_ln21_3_fu_440_p1(11 - 1 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_d0 <= gmem_in_addr_read_reg_538_pp0_iter13_reg;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln18_reg_551, trunc_ln19_reg_555)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln19_reg_555 = ap_const_lv2_0) and (trunc_ln18_reg_551 = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_address0 <= zext_ln21_3_fu_440_p1(11 - 1 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_d0 <= gmem_in_addr_read_reg_538_pp0_iter13_reg;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln18_reg_551, trunc_ln19_reg_555)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln19_reg_555 = ap_const_lv2_1) and (trunc_ln18_reg_551 = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_address0 <= zext_ln21_3_fu_440_p1(11 - 1 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_d0 <= gmem_in_addr_read_reg_538_pp0_iter13_reg;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln18_reg_551, trunc_ln19_reg_555)
    begin
        if ((not((trunc_ln19_reg_555 = ap_const_lv2_0)) and not((trunc_ln19_reg_555 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln18_reg_551 = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_address0 <= zext_ln21_3_fu_440_p1(11 - 1 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_d0 <= gmem_in_addr_read_reg_538_pp0_iter13_reg;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln18_reg_551, trunc_ln19_reg_555)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln19_reg_555 = ap_const_lv2_0) and (trunc_ln18_reg_551 = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_address0 <= zext_ln21_3_fu_440_p1(11 - 1 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_d0 <= gmem_in_addr_read_reg_538_pp0_iter13_reg;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln18_reg_551, trunc_ln19_reg_555)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln19_reg_555 = ap_const_lv2_1) and (trunc_ln18_reg_551 = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_address0 <= zext_ln21_3_fu_440_p1(11 - 1 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_d0 <= gmem_in_addr_read_reg_538_pp0_iter13_reg;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln18_reg_551, trunc_ln19_reg_555)
    begin
        if ((not((trunc_ln19_reg_555 = ap_const_lv2_0)) and not((trunc_ln19_reg_555 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln18_reg_551 = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_address0 <= zext_ln21_3_fu_440_p1(11 - 1 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_d0 <= gmem_in_addr_read_reg_538_pp0_iter13_reg;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln18_reg_551, trunc_ln19_reg_555)
    begin
        if ((not((trunc_ln18_reg_551 = ap_const_lv2_0)) and not((trunc_ln18_reg_551 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln19_reg_555 = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_address0 <= zext_ln21_3_fu_440_p1(11 - 1 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_d0 <= gmem_in_addr_read_reg_538_pp0_iter13_reg;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln18_reg_551, trunc_ln19_reg_555)
    begin
        if ((not((trunc_ln18_reg_551 = ap_const_lv2_0)) and not((trunc_ln18_reg_551 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln19_reg_555 = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_address0 <= zext_ln21_3_fu_440_p1(11 - 1 downto 0);
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_d0 <= gmem_in_addr_read_reg_538_pp0_iter13_reg;
    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0 <= p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0_local;

    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, trunc_ln18_reg_551, trunc_ln19_reg_555)
    begin
        if ((not((trunc_ln18_reg_551 = ap_const_lv2_0)) and not((trunc_ln19_reg_555 = ap_const_lv2_0)) and not((trunc_ln19_reg_555 = ap_const_lv2_1)) and not((trunc_ln18_reg_551 = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0_local <= ap_const_logic_1;
        else 
            p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln18_1_fu_305_p3 <= 
        add_ln18_fu_285_p2 when (icmp_ln19_fu_291_p2(0) = '1') else 
        r_fu_94;
    select_ln18_fu_297_p3 <= 
        ap_const_lv8_0 when (icmp_ln19_fu_291_p2(0) = '1') else 
        c_fu_90;
    shl_ln_fu_389_p3 <= (trunc_ln21_reg_502 & ap_const_lv7_0);
    tmp_fu_346_p4 <= mul_ln18_fu_340_p2(16 downto 10);
    trunc_ln18_fu_423_p1 <= grp_fu_356_p2(2 - 1 downto 0);
    trunc_ln19_fu_427_p1 <= grp_fu_384_p2(2 - 1 downto 0);
    trunc_ln21_1_fu_317_p1 <= select_ln18_fu_297_p3(7 - 1 downto 0);
    trunc_ln21_fu_313_p1 <= select_ln18_1_fu_305_p3(7 - 1 downto 0);
    zext_ln21_1_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln21_1_reg_507),32));
    zext_ln21_3_fu_440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln21_2_reg_533_pp0_iter13_reg),32));
    zext_ln21_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_389_p3),32));
end behav;
