

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
		"CDFG" : "filter_afbeelding",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_invoer", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_invoer_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_invoer_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "gmem_uitvoer", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_uitvoer_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_uitvoer_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_uitvoer_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "invoer_pixels", "Type" : "None", "Direction" : "I"},
			{"Name" : "uitvoer_pixels", "Type" : "None", "Direction" : "I"},
			{"Name" : "breedte", "Type" : "None", "Direction" : "I"},
			{"Name" : "hoogte", "Type" : "None", "Direction" : "I"},
			{"Name" : "kanalen", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "Kanalen_Wegschrijven", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "704", "FirstState" : "ap_ST_fsm_state693", "LastState" : ["ap_ST_fsm_state699"], "QuitState" : ["ap_ST_fsm_state693"], "PreState" : ["ap_ST_fsm_state692"], "PostState" : ["ap_ST_fsm_state12"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "Lus_X", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "704", "FirstState" : "ap_ST_fsm_state12", "LastState" : ["ap_ST_fsm_state693"], "QuitState" : ["ap_ST_fsm_state12"], "PreState" : ["ap_ST_fsm_state11"], "PostState" : ["ap_ST_fsm_state11"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "Lus_Y", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "704", "FirstState" : "ap_ST_fsm_state11", "LastState" : ["ap_ST_fsm_state12"], "QuitState" : ["ap_ST_fsm_state11"], "PreState" : ["ap_ST_fsm_state10"], "PostState" : ["ap_ST_fsm_state700"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.vitis_control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_invoer_m_axi_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_uitvoer_m_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fadd_32ns_32ns_32_5_full_dsp_1_U1", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.fmul_32ns_32ns_32_4_max_dsp_1_U2", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.uitofp_32ns_32_6_no_dsp_1_U3", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32ns_32ns_64_2_1_U4", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_63ns_32ns_64_5_1_U5", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_63ns_32s_64_5_1_U6", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_63s_32s_64_5_1_U7", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_64s_32ns_64_5_1_U8", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_7_2_32_1_1_U9", "Parent" : "0"}]}
