

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "6", "7", "8", "9", "10"],
		"CDFG" : "filter_afbeelding",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_invoer", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_invoer_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116", "Port" : "gmem_invoer", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "gmem_uitvoer", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116", "Port" : "gmem_uitvoer", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "invoer_pixels", "Type" : "None", "Direction" : "I"},
			{"Name" : "uitvoer_pixels", "Type" : "None", "Direction" : "I"},
			{"Name" : "breedte", "Type" : "None", "Direction" : "I"},
			{"Name" : "hoogte", "Type" : "None", "Direction" : "I"},
			{"Name" : "kanalen", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116", "Parent" : "0", "Child" : ["2", "3", "4", "5"],
		"CDFG" : "filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_uitvoer", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_uitvoer_blk_n_B", "Type" : "RtlSignal"},
					{"Name" : "gmem_uitvoer_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_uitvoer_blk_n_W", "Type" : "RtlSignal"}]},
			{"Name" : "breedte", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem_invoer", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_invoer_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "mul_ln3", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln37", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln37", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln37_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "uitvoer_pixels", "Type" : "None", "Direction" : "I"},
			{"Name" : "select_ln37_1", "Type" : "None", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "Loop_Rows_Loop_Cols", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter12", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter12", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116.line_buffer_1_U", "Parent" : "1"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116.line_buffer_U", "Parent" : "1"},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116.mul_31ns_32ns_62_2_1_U1", "Parent" : "1"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116.flow_control_loop_pipe_sequential_init_U", "Parent" : "1"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.vitis_control_s_axi_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_invoer_m_axi_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_uitvoer_m_axi_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_31ns_31ns_62_2_1_U14", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_32ns_32ns_63_2_1_U15", "Parent" : "0"}]}
