// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module apply_hardware_pooling_apply_hardware_pooling_Pipeline_Pool_X (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_out_0_AWVALID,
        m_axi_gmem_out_0_AWREADY,
        m_axi_gmem_out_0_AWADDR,
        m_axi_gmem_out_0_AWID,
        m_axi_gmem_out_0_AWLEN,
        m_axi_gmem_out_0_AWSIZE,
        m_axi_gmem_out_0_AWBURST,
        m_axi_gmem_out_0_AWLOCK,
        m_axi_gmem_out_0_AWCACHE,
        m_axi_gmem_out_0_AWPROT,
        m_axi_gmem_out_0_AWQOS,
        m_axi_gmem_out_0_AWREGION,
        m_axi_gmem_out_0_AWUSER,
        m_axi_gmem_out_0_WVALID,
        m_axi_gmem_out_0_WREADY,
        m_axi_gmem_out_0_WDATA,
        m_axi_gmem_out_0_WSTRB,
        m_axi_gmem_out_0_WLAST,
        m_axi_gmem_out_0_WID,
        m_axi_gmem_out_0_WUSER,
        m_axi_gmem_out_0_ARVALID,
        m_axi_gmem_out_0_ARREADY,
        m_axi_gmem_out_0_ARADDR,
        m_axi_gmem_out_0_ARID,
        m_axi_gmem_out_0_ARLEN,
        m_axi_gmem_out_0_ARSIZE,
        m_axi_gmem_out_0_ARBURST,
        m_axi_gmem_out_0_ARLOCK,
        m_axi_gmem_out_0_ARCACHE,
        m_axi_gmem_out_0_ARPROT,
        m_axi_gmem_out_0_ARQOS,
        m_axi_gmem_out_0_ARREGION,
        m_axi_gmem_out_0_ARUSER,
        m_axi_gmem_out_0_RVALID,
        m_axi_gmem_out_0_RREADY,
        m_axi_gmem_out_0_RDATA,
        m_axi_gmem_out_0_RLAST,
        m_axi_gmem_out_0_RID,
        m_axi_gmem_out_0_RFIFONUM,
        m_axi_gmem_out_0_RUSER,
        m_axi_gmem_out_0_RRESP,
        m_axi_gmem_out_0_BVALID,
        m_axi_gmem_out_0_BREADY,
        m_axi_gmem_out_0_BRESP,
        m_axi_gmem_out_0_BID,
        m_axi_gmem_out_0_BUSER,
        add_ln25_1,
        sext_ln40,
        rij_buffer_0_address0,
        rij_buffer_0_ce0,
        rij_buffer_0_q0,
        rij_buffer_0_address1,
        rij_buffer_0_ce1,
        rij_buffer_0_q1,
        rij_buffer_1_address0,
        rij_buffer_1_ce0,
        rij_buffer_1_q0,
        rij_buffer_1_address1,
        rij_buffer_1_ce1,
        rij_buffer_1_q1,
        mode
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_out_0_AWVALID;
input   m_axi_gmem_out_0_AWREADY;
output  [63:0] m_axi_gmem_out_0_AWADDR;
output  [0:0] m_axi_gmem_out_0_AWID;
output  [31:0] m_axi_gmem_out_0_AWLEN;
output  [2:0] m_axi_gmem_out_0_AWSIZE;
output  [1:0] m_axi_gmem_out_0_AWBURST;
output  [1:0] m_axi_gmem_out_0_AWLOCK;
output  [3:0] m_axi_gmem_out_0_AWCACHE;
output  [2:0] m_axi_gmem_out_0_AWPROT;
output  [3:0] m_axi_gmem_out_0_AWQOS;
output  [3:0] m_axi_gmem_out_0_AWREGION;
output  [0:0] m_axi_gmem_out_0_AWUSER;
output   m_axi_gmem_out_0_WVALID;
input   m_axi_gmem_out_0_WREADY;
output  [31:0] m_axi_gmem_out_0_WDATA;
output  [3:0] m_axi_gmem_out_0_WSTRB;
output   m_axi_gmem_out_0_WLAST;
output  [0:0] m_axi_gmem_out_0_WID;
output  [0:0] m_axi_gmem_out_0_WUSER;
output   m_axi_gmem_out_0_ARVALID;
input   m_axi_gmem_out_0_ARREADY;
output  [63:0] m_axi_gmem_out_0_ARADDR;
output  [0:0] m_axi_gmem_out_0_ARID;
output  [31:0] m_axi_gmem_out_0_ARLEN;
output  [2:0] m_axi_gmem_out_0_ARSIZE;
output  [1:0] m_axi_gmem_out_0_ARBURST;
output  [1:0] m_axi_gmem_out_0_ARLOCK;
output  [3:0] m_axi_gmem_out_0_ARCACHE;
output  [2:0] m_axi_gmem_out_0_ARPROT;
output  [3:0] m_axi_gmem_out_0_ARQOS;
output  [3:0] m_axi_gmem_out_0_ARREGION;
output  [0:0] m_axi_gmem_out_0_ARUSER;
input   m_axi_gmem_out_0_RVALID;
output   m_axi_gmem_out_0_RREADY;
input  [31:0] m_axi_gmem_out_0_RDATA;
input   m_axi_gmem_out_0_RLAST;
input  [0:0] m_axi_gmem_out_0_RID;
input  [8:0] m_axi_gmem_out_0_RFIFONUM;
input  [0:0] m_axi_gmem_out_0_RUSER;
input  [1:0] m_axi_gmem_out_0_RRESP;
input   m_axi_gmem_out_0_BVALID;
output   m_axi_gmem_out_0_BREADY;
input  [1:0] m_axi_gmem_out_0_BRESP;
input  [0:0] m_axi_gmem_out_0_BID;
input  [0:0] m_axi_gmem_out_0_BUSER;
input  [31:0] add_ln25_1;
input  [61:0] sext_ln40;
output  [7:0] rij_buffer_0_address0;
output   rij_buffer_0_ce0;
input  [23:0] rij_buffer_0_q0;
output  [7:0] rij_buffer_0_address1;
output   rij_buffer_0_ce1;
input  [23:0] rij_buffer_0_q1;
output  [7:0] rij_buffer_1_address0;
output   rij_buffer_1_ce0;
input  [23:0] rij_buffer_1_q0;
output  [7:0] rij_buffer_1_address1;
output   rij_buffer_1_ce1;
input  [23:0] rij_buffer_1_q1;
input  [31:0] mode;

reg ap_idle;
reg m_axi_gmem_out_0_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln40_fu_218_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_out_blk_n_W;
wire    ap_block_pp0_stage0;
wire   [31:0] mode_read_reg_782;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln40_reg_797;
wire   [7:0] val00_fu_288_p1;
reg   [7:0] val00_reg_821;
wire   [7:0] val01_fu_292_p1;
reg   [7:0] val01_reg_828;
wire   [7:0] val10_fu_296_p1;
reg   [7:0] val10_reg_835;
wire   [7:0] val11_fu_300_p1;
reg   [7:0] val11_reg_842;
wire   [7:0] val00_1_fu_304_p4;
reg   [7:0] val00_1_reg_849;
wire   [7:0] val01_1_fu_314_p4;
reg   [7:0] val01_1_reg_856;
wire   [7:0] val10_1_fu_324_p4;
reg   [7:0] val10_1_reg_863;
wire   [7:0] val11_1_fu_334_p4;
reg   [7:0] val11_1_reg_870;
wire   [7:0] val00_2_fu_344_p4;
reg   [7:0] val00_2_reg_877;
wire   [7:0] val01_2_fu_354_p4;
reg   [7:0] val01_2_reg_884;
wire   [7:0] val10_2_fu_364_p4;
reg   [7:0] val10_2_reg_891;
wire   [7:0] val11_2_fu_374_p4;
reg   [7:0] val11_2_reg_898;
wire   [0:0] icmp_ln65_fu_384_p2;
reg   [0:0] icmp_ln65_reg_905;
wire   [0:0] icmp_ln66_fu_390_p2;
reg   [0:0] icmp_ln66_reg_910;
wire   [0:0] icmp_ln65_1_fu_396_p2;
reg   [0:0] icmp_ln65_1_reg_915;
wire   [0:0] icmp_ln66_1_fu_402_p2;
reg   [0:0] icmp_ln66_1_reg_920;
wire   [0:0] icmp_ln65_2_fu_408_p2;
reg   [0:0] icmp_ln65_2_reg_925;
wire   [0:0] icmp_ln66_2_fu_414_p2;
reg   [0:0] icmp_ln66_2_reg_930;
wire   [0:0] icmp_ln73_fu_420_p2;
reg   [0:0] icmp_ln73_reg_935;
wire   [0:0] icmp_ln74_fu_426_p2;
reg   [0:0] icmp_ln74_reg_940;
wire   [0:0] icmp_ln73_1_fu_432_p2;
reg   [0:0] icmp_ln73_1_reg_945;
wire   [0:0] icmp_ln74_1_fu_438_p2;
reg   [0:0] icmp_ln74_1_reg_950;
wire   [0:0] icmp_ln73_2_fu_444_p2;
reg   [0:0] icmp_ln73_2_reg_955;
wire   [0:0] icmp_ln74_2_fu_450_p2;
reg   [0:0] icmp_ln74_2_reg_960;
wire   [7:0] final_val_5_fu_616_p3;
wire   [7:0] final_val_6_fu_640_p3;
wire   [7:0] final_val_7_fu_664_p3;
wire   [7:0] final_val_fu_688_p3;
wire   [7:0] final_val_2_fu_712_p3;
wire   [7:0] final_val_4_fu_736_p3;
wire   [7:0] ap_phi_reg_pp0_iter0_final_val_1_144_reg_168;
reg   [7:0] ap_phi_reg_pp0_iter1_final_val_1_144_reg_168;
reg   [7:0] ap_phi_reg_pp0_iter2_final_val_1_144_reg_168;
reg   [7:0] ap_phi_reg_pp0_iter3_final_val_1_144_reg_168;
reg   [7:0] ap_phi_reg_pp0_iter4_final_val_1_144_reg_168;
reg    ap_predicate_pred259_state4;
reg    ap_predicate_pred266_state4;
reg    ap_predicate_pred273_state4;
wire   [7:0] ap_phi_reg_pp0_iter0_final_val_13942_reg_179;
reg   [7:0] ap_phi_reg_pp0_iter1_final_val_13942_reg_179;
reg   [7:0] ap_phi_reg_pp0_iter2_final_val_13942_reg_179;
reg   [7:0] ap_phi_reg_pp0_iter3_final_val_13942_reg_179;
reg   [7:0] ap_phi_reg_pp0_iter4_final_val_13942_reg_179;
wire   [7:0] ap_phi_reg_pp0_iter0_final_val_11_reg_190;
reg   [7:0] ap_phi_reg_pp0_iter1_final_val_11_reg_190;
reg   [7:0] ap_phi_reg_pp0_iter2_final_val_11_reg_190;
reg   [7:0] ap_phi_reg_pp0_iter3_final_val_11_reg_190;
reg   [7:0] ap_phi_reg_pp0_iter4_final_val_11_reg_190;
wire   [63:0] zext_ln40_fu_232_p1;
wire   [63:0] zext_ln45_fu_256_p1;
wire    ap_block_pp0_stage0_01001;
reg   [32:0] x_2_fu_84;
wire   [32:0] add_ln40_fu_272_p2;
wire    ap_loop_init;
reg   [31:0] output_x_fu_88;
wire   [31:0] add_ln87_fu_223_p2;
reg    rij_buffer_0_ce1_local;
reg    rij_buffer_0_ce0_local;
reg    rij_buffer_1_ce1_local;
reg    rij_buffer_1_ce0_local;
wire   [6:0] tmp_fu_238_p4;
wire   [7:0] or_ln_fu_248_p3;
wire   [8:0] zext_ln70_1_fu_459_p1;
wire   [8:0] zext_ln70_fu_456_p1;
wire   [8:0] add_ln70_fu_468_p2;
wire   [8:0] zext_ln70_2_fu_462_p1;
wire   [8:0] zext_ln70_3_fu_465_p1;
wire   [8:0] add_ln70_1_fu_478_p2;
wire   [9:0] zext_ln70_5_fu_484_p1;
wire   [9:0] zext_ln70_4_fu_474_p1;
wire   [9:0] add_ln70_2_fu_488_p2;
wire   [8:0] zext_ln70_7_fu_507_p1;
wire   [8:0] zext_ln70_6_fu_504_p1;
wire   [8:0] add_ln70_3_fu_516_p2;
wire   [8:0] zext_ln70_8_fu_510_p1;
wire   [8:0] zext_ln70_9_fu_513_p1;
wire   [8:0] add_ln70_4_fu_526_p2;
wire   [9:0] zext_ln70_11_fu_532_p1;
wire   [9:0] zext_ln70_10_fu_522_p1;
wire   [9:0] add_ln70_5_fu_536_p2;
wire   [8:0] zext_ln70_13_fu_555_p1;
wire   [8:0] zext_ln70_12_fu_552_p1;
wire   [8:0] add_ln70_6_fu_564_p2;
wire   [8:0] zext_ln70_14_fu_558_p1;
wire   [8:0] zext_ln70_15_fu_561_p1;
wire   [8:0] add_ln70_7_fu_574_p2;
wire   [9:0] zext_ln70_17_fu_580_p1;
wire   [9:0] zext_ln70_16_fu_570_p1;
wire   [9:0] add_ln70_8_fu_584_p2;
wire   [7:0] max1_fu_600_p3;
wire   [7:0] max2_fu_605_p3;
wire   [0:0] icmp_ln67_fu_610_p2;
wire   [7:0] max1_1_fu_624_p3;
wire   [7:0] max2_1_fu_629_p3;
wire   [0:0] icmp_ln67_1_fu_634_p2;
wire   [7:0] max1_2_fu_648_p3;
wire   [7:0] max2_2_fu_653_p3;
wire   [0:0] icmp_ln67_2_fu_658_p2;
wire   [7:0] min1_fu_672_p3;
wire   [7:0] min2_fu_677_p3;
wire   [0:0] icmp_ln75_fu_682_p2;
wire   [7:0] min1_1_fu_696_p3;
wire   [7:0] min2_1_fu_701_p3;
wire   [0:0] icmp_ln75_1_fu_706_p2;
wire   [7:0] min1_2_fu_720_p3;
wire   [7:0] min2_2_fu_725_p3;
wire   [0:0] icmp_ln75_2_fu_730_p2;
wire   [24:0] res_pixel_fu_750_p5;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 x_2_fu_84 = 33'd0;
#0 output_x_fu_88 = 32'd0;
#0 ap_done_reg = 1'b0;
end

apply_hardware_pooling_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((ap_predicate_pred273_state4 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_final_val_11_reg_190 <= final_val_4_fu_736_p3;
        end else if ((ap_predicate_pred266_state4 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_final_val_11_reg_190 <= {{add_ln70_8_fu_584_p2[9:2]}};
        end else if ((ap_predicate_pred259_state4 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_final_val_11_reg_190 <= final_val_7_fu_664_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_final_val_11_reg_190 <= ap_phi_reg_pp0_iter3_final_val_11_reg_190;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((ap_predicate_pred273_state4 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_final_val_13942_reg_179 <= final_val_fu_688_p3;
        end else if ((ap_predicate_pred266_state4 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_final_val_13942_reg_179 <= {{add_ln70_2_fu_488_p2[9:2]}};
        end else if ((ap_predicate_pred259_state4 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_final_val_13942_reg_179 <= final_val_5_fu_616_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_final_val_13942_reg_179 <= ap_phi_reg_pp0_iter3_final_val_13942_reg_179;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((ap_predicate_pred273_state4 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_final_val_1_144_reg_168 <= final_val_2_fu_712_p3;
        end else if ((ap_predicate_pred266_state4 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_final_val_1_144_reg_168 <= {{add_ln70_5_fu_536_p2[9:2]}};
        end else if ((ap_predicate_pred259_state4 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_final_val_1_144_reg_168 <= final_val_6_fu_640_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_final_val_1_144_reg_168 <= ap_phi_reg_pp0_iter3_final_val_1_144_reg_168;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            output_x_fu_88 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln40_fu_218_p2 == 1'd0))) begin
            output_x_fu_88 <= add_ln87_fu_223_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            x_2_fu_84 <= 33'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln40_fu_218_p2 == 1'd0))) begin
            x_2_fu_84 <= add_ln40_fu_272_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln40_reg_797 <= icmp_ln40_fu_218_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_predicate_pred259_state4 <= ((icmp_ln40_reg_797 == 1'd0) & (mode_read_reg_782 == 32'd0));
        ap_predicate_pred266_state4 <= ((icmp_ln40_reg_797 == 1'd0) & (mode_read_reg_782 == 32'd1));
        ap_predicate_pred273_state4 <= (~(mode_read_reg_782 == 32'd1) & ~(mode_read_reg_782 == 32'd0) & (icmp_ln40_reg_797 == 1'd0));
        icmp_ln65_1_reg_915 <= icmp_ln65_1_fu_396_p2;
        icmp_ln65_2_reg_925 <= icmp_ln65_2_fu_408_p2;
        icmp_ln65_reg_905 <= icmp_ln65_fu_384_p2;
        icmp_ln66_1_reg_920 <= icmp_ln66_1_fu_402_p2;
        icmp_ln66_2_reg_930 <= icmp_ln66_2_fu_414_p2;
        icmp_ln66_reg_910 <= icmp_ln66_fu_390_p2;
        icmp_ln73_1_reg_945 <= icmp_ln73_1_fu_432_p2;
        icmp_ln73_2_reg_955 <= icmp_ln73_2_fu_444_p2;
        icmp_ln73_reg_935 <= icmp_ln73_fu_420_p2;
        icmp_ln74_1_reg_950 <= icmp_ln74_1_fu_438_p2;
        icmp_ln74_2_reg_960 <= icmp_ln74_2_fu_450_p2;
        icmp_ln74_reg_940 <= icmp_ln74_fu_426_p2;
        val00_1_reg_849 <= {{rij_buffer_0_q1[15:8]}};
        val00_2_reg_877 <= {{rij_buffer_0_q1[23:16]}};
        val00_reg_821 <= val00_fu_288_p1;
        val01_1_reg_856 <= {{rij_buffer_0_q0[15:8]}};
        val01_2_reg_884 <= {{rij_buffer_0_q0[23:16]}};
        val01_reg_828 <= val01_fu_292_p1;
        val10_1_reg_863 <= {{rij_buffer_1_q1[15:8]}};
        val10_2_reg_891 <= {{rij_buffer_1_q1[23:16]}};
        val10_reg_835 <= val10_fu_296_p1;
        val11_1_reg_870 <= {{rij_buffer_1_q0[15:8]}};
        val11_2_reg_898 <= {{rij_buffer_1_q0[23:16]}};
        val11_reg_842 <= val11_fu_300_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_final_val_11_reg_190 <= ap_phi_reg_pp0_iter0_final_val_11_reg_190;
        ap_phi_reg_pp0_iter1_final_val_13942_reg_179 <= ap_phi_reg_pp0_iter0_final_val_13942_reg_179;
        ap_phi_reg_pp0_iter1_final_val_1_144_reg_168 <= ap_phi_reg_pp0_iter0_final_val_1_144_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_final_val_11_reg_190 <= ap_phi_reg_pp0_iter1_final_val_11_reg_190;
        ap_phi_reg_pp0_iter2_final_val_13942_reg_179 <= ap_phi_reg_pp0_iter1_final_val_13942_reg_179;
        ap_phi_reg_pp0_iter2_final_val_1_144_reg_168 <= ap_phi_reg_pp0_iter1_final_val_1_144_reg_168;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_final_val_11_reg_190 <= ap_phi_reg_pp0_iter2_final_val_11_reg_190;
        ap_phi_reg_pp0_iter3_final_val_13942_reg_179 <= ap_phi_reg_pp0_iter2_final_val_13942_reg_179;
        ap_phi_reg_pp0_iter3_final_val_1_144_reg_168 <= ap_phi_reg_pp0_iter2_final_val_1_144_reg_168;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln40_fu_218_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        gmem_out_blk_n_W = m_axi_gmem_out_0_WREADY;
    end else begin
        gmem_out_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        m_axi_gmem_out_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem_out_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rij_buffer_0_ce0_local = 1'b1;
    end else begin
        rij_buffer_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rij_buffer_0_ce1_local = 1'b1;
    end else begin
        rij_buffer_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rij_buffer_1_ce0_local = 1'b1;
    end else begin
        rij_buffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rij_buffer_1_ce1_local = 1'b1;
    end else begin
        rij_buffer_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln40_fu_272_p2 = (x_2_fu_84 + 33'd2);

assign add_ln70_1_fu_478_p2 = (zext_ln70_2_fu_462_p1 + zext_ln70_3_fu_465_p1);

assign add_ln70_2_fu_488_p2 = (zext_ln70_5_fu_484_p1 + zext_ln70_4_fu_474_p1);

assign add_ln70_3_fu_516_p2 = (zext_ln70_7_fu_507_p1 + zext_ln70_6_fu_504_p1);

assign add_ln70_4_fu_526_p2 = (zext_ln70_8_fu_510_p1 + zext_ln70_9_fu_513_p1);

assign add_ln70_5_fu_536_p2 = (zext_ln70_11_fu_532_p1 + zext_ln70_10_fu_522_p1);

assign add_ln70_6_fu_564_p2 = (zext_ln70_13_fu_555_p1 + zext_ln70_12_fu_552_p1);

assign add_ln70_7_fu_574_p2 = (zext_ln70_14_fu_558_p1 + zext_ln70_15_fu_561_p1);

assign add_ln70_8_fu_584_p2 = (zext_ln70_17_fu_580_p1 + zext_ln70_16_fu_570_p1);

assign add_ln70_fu_468_p2 = (zext_ln70_1_fu_459_p1 + zext_ln70_fu_456_p1);

assign add_ln87_fu_223_p2 = (output_x_fu_88 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem_out_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem_out_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter0_final_val_11_reg_190 = 'bx;

assign ap_phi_reg_pp0_iter0_final_val_13942_reg_179 = 'bx;

assign ap_phi_reg_pp0_iter0_final_val_1_144_reg_168 = 'bx;

assign ap_ready = ap_ready_sig;

assign final_val_2_fu_712_p3 = ((icmp_ln75_1_fu_706_p2[0:0] == 1'b1) ? min1_1_fu_696_p3 : min2_1_fu_701_p3);

assign final_val_4_fu_736_p3 = ((icmp_ln75_2_fu_730_p2[0:0] == 1'b1) ? min1_2_fu_720_p3 : min2_2_fu_725_p3);

assign final_val_5_fu_616_p3 = ((icmp_ln67_fu_610_p2[0:0] == 1'b1) ? max1_fu_600_p3 : max2_fu_605_p3);

assign final_val_6_fu_640_p3 = ((icmp_ln67_1_fu_634_p2[0:0] == 1'b1) ? max1_1_fu_624_p3 : max2_1_fu_629_p3);

assign final_val_7_fu_664_p3 = ((icmp_ln67_2_fu_658_p2[0:0] == 1'b1) ? max1_2_fu_648_p3 : max2_2_fu_653_p3);

assign final_val_fu_688_p3 = ((icmp_ln75_fu_682_p2[0:0] == 1'b1) ? min1_fu_672_p3 : min2_fu_677_p3);

assign icmp_ln40_fu_218_p2 = ((output_x_fu_88 == add_ln25_1) ? 1'b1 : 1'b0);

assign icmp_ln65_1_fu_396_p2 = ((val00_1_fu_304_p4 > val01_1_fu_314_p4) ? 1'b1 : 1'b0);

assign icmp_ln65_2_fu_408_p2 = ((val00_2_fu_344_p4 > val01_2_fu_354_p4) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_384_p2 = ((val00_fu_288_p1 > val01_fu_292_p1) ? 1'b1 : 1'b0);

assign icmp_ln66_1_fu_402_p2 = ((val10_1_fu_324_p4 > val11_1_fu_334_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_414_p2 = ((val10_2_fu_364_p4 > val11_2_fu_374_p4) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_390_p2 = ((val10_fu_296_p1 > val11_fu_300_p1) ? 1'b1 : 1'b0);

assign icmp_ln67_1_fu_634_p2 = ((max1_1_fu_624_p3 > max2_1_fu_629_p3) ? 1'b1 : 1'b0);

assign icmp_ln67_2_fu_658_p2 = ((max1_2_fu_648_p3 > max2_2_fu_653_p3) ? 1'b1 : 1'b0);

assign icmp_ln67_fu_610_p2 = ((max1_fu_600_p3 > max2_fu_605_p3) ? 1'b1 : 1'b0);

assign icmp_ln73_1_fu_432_p2 = ((val00_1_fu_304_p4 < val01_1_fu_314_p4) ? 1'b1 : 1'b0);

assign icmp_ln73_2_fu_444_p2 = ((val00_2_fu_344_p4 < val01_2_fu_354_p4) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_420_p2 = ((val00_fu_288_p1 < val01_fu_292_p1) ? 1'b1 : 1'b0);

assign icmp_ln74_1_fu_438_p2 = ((val10_1_fu_324_p4 < val11_1_fu_334_p4) ? 1'b1 : 1'b0);

assign icmp_ln74_2_fu_450_p2 = ((val10_2_fu_364_p4 < val11_2_fu_374_p4) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_426_p2 = ((val10_fu_296_p1 < val11_fu_300_p1) ? 1'b1 : 1'b0);

assign icmp_ln75_1_fu_706_p2 = ((min1_1_fu_696_p3 < min2_1_fu_701_p3) ? 1'b1 : 1'b0);

assign icmp_ln75_2_fu_730_p2 = ((min1_2_fu_720_p3 < min2_2_fu_725_p3) ? 1'b1 : 1'b0);

assign icmp_ln75_fu_682_p2 = ((min1_fu_672_p3 < min2_fu_677_p3) ? 1'b1 : 1'b0);

assign m_axi_gmem_out_0_ARADDR = 64'd0;

assign m_axi_gmem_out_0_ARBURST = 2'd0;

assign m_axi_gmem_out_0_ARCACHE = 4'd0;

assign m_axi_gmem_out_0_ARID = 1'd0;

assign m_axi_gmem_out_0_ARLEN = 32'd0;

assign m_axi_gmem_out_0_ARLOCK = 2'd0;

assign m_axi_gmem_out_0_ARPROT = 3'd0;

assign m_axi_gmem_out_0_ARQOS = 4'd0;

assign m_axi_gmem_out_0_ARREGION = 4'd0;

assign m_axi_gmem_out_0_ARSIZE = 3'd0;

assign m_axi_gmem_out_0_ARUSER = 1'd0;

assign m_axi_gmem_out_0_ARVALID = 1'b0;

assign m_axi_gmem_out_0_AWADDR = 64'd0;

assign m_axi_gmem_out_0_AWBURST = 2'd0;

assign m_axi_gmem_out_0_AWCACHE = 4'd0;

assign m_axi_gmem_out_0_AWID = 1'd0;

assign m_axi_gmem_out_0_AWLEN = 32'd0;

assign m_axi_gmem_out_0_AWLOCK = 2'd0;

assign m_axi_gmem_out_0_AWPROT = 3'd0;

assign m_axi_gmem_out_0_AWQOS = 4'd0;

assign m_axi_gmem_out_0_AWREGION = 4'd0;

assign m_axi_gmem_out_0_AWSIZE = 3'd0;

assign m_axi_gmem_out_0_AWUSER = 1'd0;

assign m_axi_gmem_out_0_AWVALID = 1'b0;

assign m_axi_gmem_out_0_BREADY = 1'b0;

assign m_axi_gmem_out_0_RREADY = 1'b0;

assign m_axi_gmem_out_0_WDATA = $signed(res_pixel_fu_750_p5);

assign m_axi_gmem_out_0_WID = 1'd0;

assign m_axi_gmem_out_0_WLAST = 1'b0;

assign m_axi_gmem_out_0_WSTRB = 4'd15;

assign m_axi_gmem_out_0_WUSER = 1'd0;

assign max1_1_fu_624_p3 = ((icmp_ln65_1_reg_915[0:0] == 1'b1) ? val00_1_reg_849 : val01_1_reg_856);

assign max1_2_fu_648_p3 = ((icmp_ln65_2_reg_925[0:0] == 1'b1) ? val00_2_reg_877 : val01_2_reg_884);

assign max1_fu_600_p3 = ((icmp_ln65_reg_905[0:0] == 1'b1) ? val00_reg_821 : val01_reg_828);

assign max2_1_fu_629_p3 = ((icmp_ln66_1_reg_920[0:0] == 1'b1) ? val10_1_reg_863 : val11_1_reg_870);

assign max2_2_fu_653_p3 = ((icmp_ln66_2_reg_930[0:0] == 1'b1) ? val10_2_reg_891 : val11_2_reg_898);

assign max2_fu_605_p3 = ((icmp_ln66_reg_910[0:0] == 1'b1) ? val10_reg_835 : val11_reg_842);

assign min1_1_fu_696_p3 = ((icmp_ln73_1_reg_945[0:0] == 1'b1) ? val00_1_reg_849 : val01_1_reg_856);

assign min1_2_fu_720_p3 = ((icmp_ln73_2_reg_955[0:0] == 1'b1) ? val00_2_reg_877 : val01_2_reg_884);

assign min1_fu_672_p3 = ((icmp_ln73_reg_935[0:0] == 1'b1) ? val00_reg_821 : val01_reg_828);

assign min2_1_fu_701_p3 = ((icmp_ln74_1_reg_950[0:0] == 1'b1) ? val10_1_reg_863 : val11_1_reg_870);

assign min2_2_fu_725_p3 = ((icmp_ln74_2_reg_960[0:0] == 1'b1) ? val10_2_reg_891 : val11_2_reg_898);

assign min2_fu_677_p3 = ((icmp_ln74_reg_940[0:0] == 1'b1) ? val10_reg_835 : val11_reg_842);

assign mode_read_reg_782 = mode;

assign or_ln_fu_248_p3 = {{tmp_fu_238_p4}, {1'd1}};

assign res_pixel_fu_750_p5 = {{{{{{1'd1}, {ap_phi_reg_pp0_iter4_final_val_11_reg_190}}}, {ap_phi_reg_pp0_iter4_final_val_1_144_reg_168}}}, {ap_phi_reg_pp0_iter4_final_val_13942_reg_179}};

assign rij_buffer_0_address0 = zext_ln45_fu_256_p1;

assign rij_buffer_0_address1 = zext_ln40_fu_232_p1;

assign rij_buffer_0_ce0 = rij_buffer_0_ce0_local;

assign rij_buffer_0_ce1 = rij_buffer_0_ce1_local;

assign rij_buffer_1_address0 = zext_ln45_fu_256_p1;

assign rij_buffer_1_address1 = zext_ln40_fu_232_p1;

assign rij_buffer_1_ce0 = rij_buffer_1_ce0_local;

assign rij_buffer_1_ce1 = rij_buffer_1_ce1_local;

assign tmp_fu_238_p4 = {{x_2_fu_84[7:1]}};

assign val00_1_fu_304_p4 = {{rij_buffer_0_q1[15:8]}};

assign val00_2_fu_344_p4 = {{rij_buffer_0_q1[23:16]}};

assign val00_fu_288_p1 = rij_buffer_0_q1[7:0];

assign val01_1_fu_314_p4 = {{rij_buffer_0_q0[15:8]}};

assign val01_2_fu_354_p4 = {{rij_buffer_0_q0[23:16]}};

assign val01_fu_292_p1 = rij_buffer_0_q0[7:0];

assign val10_1_fu_324_p4 = {{rij_buffer_1_q1[15:8]}};

assign val10_2_fu_364_p4 = {{rij_buffer_1_q1[23:16]}};

assign val10_fu_296_p1 = rij_buffer_1_q1[7:0];

assign val11_1_fu_334_p4 = {{rij_buffer_1_q0[15:8]}};

assign val11_2_fu_374_p4 = {{rij_buffer_1_q0[23:16]}};

assign val11_fu_300_p1 = rij_buffer_1_q0[7:0];

assign zext_ln40_fu_232_p1 = x_2_fu_84;

assign zext_ln45_fu_256_p1 = or_ln_fu_248_p3;

assign zext_ln70_10_fu_522_p1 = add_ln70_3_fu_516_p2;

assign zext_ln70_11_fu_532_p1 = add_ln70_4_fu_526_p2;

assign zext_ln70_12_fu_552_p1 = val00_2_reg_877;

assign zext_ln70_13_fu_555_p1 = val01_2_reg_884;

assign zext_ln70_14_fu_558_p1 = val10_2_reg_891;

assign zext_ln70_15_fu_561_p1 = val11_2_reg_898;

assign zext_ln70_16_fu_570_p1 = add_ln70_6_fu_564_p2;

assign zext_ln70_17_fu_580_p1 = add_ln70_7_fu_574_p2;

assign zext_ln70_1_fu_459_p1 = val01_reg_828;

assign zext_ln70_2_fu_462_p1 = val10_reg_835;

assign zext_ln70_3_fu_465_p1 = val11_reg_842;

assign zext_ln70_4_fu_474_p1 = add_ln70_fu_468_p2;

assign zext_ln70_5_fu_484_p1 = add_ln70_1_fu_478_p2;

assign zext_ln70_6_fu_504_p1 = val00_1_reg_849;

assign zext_ln70_7_fu_507_p1 = val01_1_reg_856;

assign zext_ln70_8_fu_510_p1 = val10_1_reg_863;

assign zext_ln70_9_fu_513_p1 = val11_1_reg_870;

assign zext_ln70_fu_456_p1 = val00_reg_821;

endmodule //apply_hardware_pooling_apply_hardware_pooling_Pipeline_Pool_X
