[hls]
relative_roots=C:/2EAI-HAC-2526-TaskHLS-bj-mk-tm/2D_Convolutie_HLS
# Inferred from syn.array_partition.complete_threshold=4
syn.directive.array_partition=filter_afbeelding/kleur_som dim=1 type=complete variable=kleur_som


