

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "18", "58", "60", "61", "62", "63"],
		"CDFG" : "vitis_convolution",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "48701", "EstimateLatencyMax" : "48701",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_in", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204", "Port" : "gmem_in", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "gmem_out", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "58", "SubInstance" : "grp_vitis_convolution_Pipeline_Write_Rows_Write_Cols_fu_264", "Port" : "gmem_out", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "input_img", "Type" : "None", "Direction" : "I"},
			{"Name" : "output_img", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "18", "SubInstance" : "grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "18", "SubInstance" : "grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "18", "SubInstance" : "grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "18", "SubInstance" : "grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "18", "SubInstance" : "grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "18", "SubInstance" : "grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "18", "SubInstance" : "grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "18", "SubInstance" : "grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "18", "SubInstance" : "grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230", "Port" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "local_output", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "18", "SubInstance" : "grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230", "Port" : "local_output", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "58", "SubInstance" : "grp_vitis_convolution_Pipeline_Write_Rows_Write_Cols_fu_264", "Port" : "local_output", "Inst_start_state" : "12", "Inst_end_state" : "13"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.local_output_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204", "Parent" : "0", "Child" : ["12", "13", "14", "15", "16", "17"],
		"CDFG" : "vitis_convolution_Pipeline_Read_Rows_Read_Cols",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16399", "EstimateLatencyMax" : "16399",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_in", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem_in_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem_in_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "input_img", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "Read_Rows_Read_Cols", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter14", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter14", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204.mul_8ns_10ns_17_1_1_U1", "Parent" : "11"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204.urem_8ns_3ns_2_12_1_U2", "Parent" : "11"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204.mul_8ns_10ns_17_1_1_U3", "Parent" : "11"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204.urem_8ns_3ns_2_12_1_U4", "Parent" : "11"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204.mac_muladd_7ns_6ns_7ns_11_4_1_U5", "Parent" : "11"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Read_Rows_Read_Cols_fu_204.flow_control_loop_pipe_sequential_init_U", "Parent" : "11"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230", "Parent" : "0", "Child" : ["19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57"],
		"CDFG" : "vitis_convolution_Pipeline_Conv_Rows_Conv_Cols",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "15896", "EstimateLatencyMax" : "15896",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "kernel_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_load_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_load_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_load_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_load_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_load_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_load_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_load_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "kernel_load_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "local_output", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "Conv_Rows_Conv_Cols", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter19", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter19", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U20", "Parent" : "18"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U21", "Parent" : "18"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U22", "Parent" : "18"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U23", "Parent" : "18"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U24", "Parent" : "18"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U25", "Parent" : "18"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U26", "Parent" : "18"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U27", "Parent" : "18"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U28", "Parent" : "18"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.urem_7ns_3ns_2_11_1_U29", "Parent" : "18"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mul_7ns_9ns_15_1_1_U30", "Parent" : "18"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.urem_7ns_3ns_2_11_1_U31", "Parent" : "18"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mul_7ns_9ns_15_1_1_U32", "Parent" : "18"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mul_7ns_9ns_15_1_1_U33", "Parent" : "18"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mul_7ns_9ns_15_1_1_U34", "Parent" : "18"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mul_6ns_7ns_11_1_1_U35", "Parent" : "18"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mul_6ns_7ns_11_1_1_U36", "Parent" : "18"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mul_6ns_7ns_11_1_1_U37", "Parent" : "18"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mul_7ns_9ns_15_1_1_U38", "Parent" : "18"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mul_7ns_9ns_15_1_1_U39", "Parent" : "18"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U40", "Parent" : "18"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U41", "Parent" : "18"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U42", "Parent" : "18"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U43", "Parent" : "18"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U44", "Parent" : "18"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U45", "Parent" : "18"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U46", "Parent" : "18"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U47", "Parent" : "18"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.sparsemux_7_2_8_1_1_U48", "Parent" : "18"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mul_8s_8s_8_1_1_U49", "Parent" : "18"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mul_8s_8s_8_1_1_U50", "Parent" : "18"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mul_8s_8s_8_1_1_U51", "Parent" : "18"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mul_8s_8s_8_1_1_U52", "Parent" : "18"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mac_muladd_8s_8s_8s_8_4_1_U53", "Parent" : "18"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mac_muladd_8s_8s_8s_8_4_1_U54", "Parent" : "18"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mac_muladd_8s_8s_8s_8_4_1_U55", "Parent" : "18"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mac_muladd_8s_8s_8s_8_4_1_U56", "Parent" : "18"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.mac_muladd_8s_8s_8s_8_4_1_U57", "Parent" : "18"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Conv_Rows_Conv_Cols_fu_230.flow_control_loop_pipe_sequential_init_U", "Parent" : "18"},
	{"ID" : "58", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Write_Rows_Write_Cols_fu_264", "Parent" : "0", "Child" : ["59"],
		"CDFG" : "vitis_convolution_Pipeline_Write_Rows_Write_Cols",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16394", "EstimateLatencyMax" : "16394",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem_out", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem_out_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem_out_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem_out_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "output_img", "Type" : "None", "Direction" : "I"},
			{"Name" : "local_output", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "Write_Rows_Write_Cols", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter9", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter9", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_vitis_convolution_Pipeline_Write_Rows_Write_Cols_fu_264.flow_control_loop_pipe_sequential_init_U", "Parent" : "58"},
	{"ID" : "60", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "61", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_r_s_axi_U", "Parent" : "0"},
	{"ID" : "62", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_in_m_axi_U", "Parent" : "0"},
	{"ID" : "63", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_out_m_axi_U", "Parent" : "0"}]}
