-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity apply_hardware_pooling_apply_hardware_pooling_Pipeline_Pool_X is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_out_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_out_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_out_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_out_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_out_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_out_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_out_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_out_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_out_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_out_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_out_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_out_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_out_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_out_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_out_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_out_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_out_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_out_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_out_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_out_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_out_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_out_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_out_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_out_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    add_ln25_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln40 : IN STD_LOGIC_VECTOR (61 downto 0);
    rij_buffer_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rij_buffer_0_ce0 : OUT STD_LOGIC;
    rij_buffer_0_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    rij_buffer_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rij_buffer_0_ce1 : OUT STD_LOGIC;
    rij_buffer_0_q1 : IN STD_LOGIC_VECTOR (23 downto 0);
    rij_buffer_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rij_buffer_1_ce0 : OUT STD_LOGIC;
    rij_buffer_1_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    rij_buffer_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    rij_buffer_1_ce1 : OUT STD_LOGIC;
    rij_buffer_1_q1 : IN STD_LOGIC_VECTOR (23 downto 0);
    mode : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of apply_hardware_pooling_apply_hardware_pooling_Pipeline_Pool_X is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv33_0 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv33_2 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln40_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_out_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mode_read_reg_782 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln40_reg_797 : STD_LOGIC_VECTOR (0 downto 0);
    signal val00_fu_288_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal val00_reg_821 : STD_LOGIC_VECTOR (7 downto 0);
    signal val01_fu_292_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal val01_reg_828 : STD_LOGIC_VECTOR (7 downto 0);
    signal val10_fu_296_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal val10_reg_835 : STD_LOGIC_VECTOR (7 downto 0);
    signal val11_fu_300_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal val11_reg_842 : STD_LOGIC_VECTOR (7 downto 0);
    signal val00_1_fu_304_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal val00_1_reg_849 : STD_LOGIC_VECTOR (7 downto 0);
    signal val01_1_fu_314_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal val01_1_reg_856 : STD_LOGIC_VECTOR (7 downto 0);
    signal val10_1_fu_324_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal val10_1_reg_863 : STD_LOGIC_VECTOR (7 downto 0);
    signal val11_1_fu_334_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal val11_1_reg_870 : STD_LOGIC_VECTOR (7 downto 0);
    signal val00_2_fu_344_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal val00_2_reg_877 : STD_LOGIC_VECTOR (7 downto 0);
    signal val01_2_fu_354_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal val01_2_reg_884 : STD_LOGIC_VECTOR (7 downto 0);
    signal val10_2_fu_364_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal val10_2_reg_891 : STD_LOGIC_VECTOR (7 downto 0);
    signal val11_2_fu_374_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal val11_2_reg_898 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln65_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_reg_905 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_reg_910 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_1_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_1_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_1_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_1_reg_920 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_2_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln65_2_reg_925 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_2_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_2_reg_930 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_reg_935 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_reg_940 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_1_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_1_reg_945 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_1_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_1_reg_950 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_2_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_2_reg_955 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_2_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln74_2_reg_960 : STD_LOGIC_VECTOR (0 downto 0);
    signal final_val_5_fu_616_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal final_val_6_fu_640_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal final_val_7_fu_664_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal final_val_fu_688_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal final_val_2_fu_712_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal final_val_4_fu_736_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_final_val_1_144_reg_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_final_val_1_144_reg_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_final_val_1_144_reg_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_final_val_1_144_reg_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter4_final_val_1_144_reg_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_predicate_pred259_state4 : BOOLEAN;
    signal ap_predicate_pred266_state4 : BOOLEAN;
    signal ap_predicate_pred273_state4 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_final_val_13942_reg_179 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_final_val_13942_reg_179 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_final_val_13942_reg_179 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_final_val_13942_reg_179 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter4_final_val_13942_reg_179 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_final_val_11_reg_190 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_final_val_11_reg_190 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_final_val_11_reg_190 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_final_val_11_reg_190 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter4_final_val_11_reg_190 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln40_fu_232_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_fu_256_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal x_2_fu_84 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";
    signal add_ln40_fu_272_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal output_x_fu_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln87_fu_223_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rij_buffer_0_ce1_local : STD_LOGIC;
    signal rij_buffer_0_ce0_local : STD_LOGIC;
    signal rij_buffer_1_ce1_local : STD_LOGIC;
    signal rij_buffer_1_ce0_local : STD_LOGIC;
    signal tmp_fu_238_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln_fu_248_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln70_1_fu_459_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_fu_456_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln70_fu_468_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_2_fu_462_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_3_fu_465_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln70_1_fu_478_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_5_fu_484_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln70_4_fu_474_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln70_2_fu_488_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln70_7_fu_507_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_6_fu_504_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln70_3_fu_516_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_8_fu_510_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_9_fu_513_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln70_4_fu_526_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_11_fu_532_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln70_10_fu_522_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln70_5_fu_536_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln70_13_fu_555_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_12_fu_552_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln70_6_fu_564_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_14_fu_558_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_15_fu_561_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln70_7_fu_574_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_17_fu_580_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln70_16_fu_570_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln70_8_fu_584_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal max1_fu_600_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal max2_fu_605_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln67_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max1_1_fu_624_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal max2_1_fu_629_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln67_1_fu_634_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal max1_2_fu_648_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal max2_2_fu_653_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln67_2_fu_658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal min1_fu_672_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal min2_fu_677_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln75_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal min1_1_fu_696_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal min2_1_fu_701_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln75_1_fu_706_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal min1_2_fu_720_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal min2_2_fu_725_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln75_2_fu_730_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_pixel_fu_750_p5 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component apply_hardware_pooling_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component apply_hardware_pooling_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter4_final_val_11_reg_190_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                if ((ap_predicate_pred273_state4 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_final_val_11_reg_190 <= final_val_4_fu_736_p3;
                elsif ((ap_predicate_pred266_state4 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_final_val_11_reg_190 <= add_ln70_8_fu_584_p2(9 downto 2);
                elsif ((ap_predicate_pred259_state4 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_final_val_11_reg_190 <= final_val_7_fu_664_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_final_val_11_reg_190 <= ap_phi_reg_pp0_iter3_final_val_11_reg_190;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter4_final_val_13942_reg_179_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                if ((ap_predicate_pred273_state4 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_final_val_13942_reg_179 <= final_val_fu_688_p3;
                elsif ((ap_predicate_pred266_state4 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_final_val_13942_reg_179 <= add_ln70_2_fu_488_p2(9 downto 2);
                elsif ((ap_predicate_pred259_state4 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_final_val_13942_reg_179 <= final_val_5_fu_616_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_final_val_13942_reg_179 <= ap_phi_reg_pp0_iter3_final_val_13942_reg_179;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter4_final_val_1_144_reg_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                if ((ap_predicate_pred273_state4 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_final_val_1_144_reg_168 <= final_val_2_fu_712_p3;
                elsif ((ap_predicate_pred266_state4 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_final_val_1_144_reg_168 <= add_ln70_5_fu_536_p2(9 downto 2);
                elsif ((ap_predicate_pred259_state4 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_final_val_1_144_reg_168 <= final_val_6_fu_640_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_final_val_1_144_reg_168 <= ap_phi_reg_pp0_iter3_final_val_1_144_reg_168;
                end if;
            end if; 
        end if;
    end process;

    output_x_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    output_x_fu_88 <= ap_const_lv32_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln40_fu_218_p2 = ap_const_lv1_0))) then 
                    output_x_fu_88 <= add_ln87_fu_223_p2;
                end if;
            end if; 
        end if;
    end process;

    x_2_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    x_2_fu_84 <= ap_const_lv33_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln40_fu_218_p2 = ap_const_lv1_0))) then 
                    x_2_fu_84 <= add_ln40_fu_272_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln40_reg_797 <= icmp_ln40_fu_218_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                    ap_predicate_pred259_state4 <= ((icmp_ln40_reg_797 = ap_const_lv1_0) and (mode_read_reg_782 = ap_const_lv32_0));
                    ap_predicate_pred266_state4 <= ((icmp_ln40_reg_797 = ap_const_lv1_0) and (mode_read_reg_782 = ap_const_lv32_1));
                    ap_predicate_pred273_state4 <= (not((mode_read_reg_782 = ap_const_lv32_1)) and not((mode_read_reg_782 = ap_const_lv32_0)) and (icmp_ln40_reg_797 = ap_const_lv1_0));
                icmp_ln65_1_reg_915 <= icmp_ln65_1_fu_396_p2;
                icmp_ln65_2_reg_925 <= icmp_ln65_2_fu_408_p2;
                icmp_ln65_reg_905 <= icmp_ln65_fu_384_p2;
                icmp_ln66_1_reg_920 <= icmp_ln66_1_fu_402_p2;
                icmp_ln66_2_reg_930 <= icmp_ln66_2_fu_414_p2;
                icmp_ln66_reg_910 <= icmp_ln66_fu_390_p2;
                icmp_ln73_1_reg_945 <= icmp_ln73_1_fu_432_p2;
                icmp_ln73_2_reg_955 <= icmp_ln73_2_fu_444_p2;
                icmp_ln73_reg_935 <= icmp_ln73_fu_420_p2;
                icmp_ln74_1_reg_950 <= icmp_ln74_1_fu_438_p2;
                icmp_ln74_2_reg_960 <= icmp_ln74_2_fu_450_p2;
                icmp_ln74_reg_940 <= icmp_ln74_fu_426_p2;
                val00_1_reg_849 <= rij_buffer_0_q1(15 downto 8);
                val00_2_reg_877 <= rij_buffer_0_q1(23 downto 16);
                val00_reg_821 <= val00_fu_288_p1;
                val01_1_reg_856 <= rij_buffer_0_q0(15 downto 8);
                val01_2_reg_884 <= rij_buffer_0_q0(23 downto 16);
                val01_reg_828 <= val01_fu_292_p1;
                val10_1_reg_863 <= rij_buffer_1_q1(15 downto 8);
                val10_2_reg_891 <= rij_buffer_1_q1(23 downto 16);
                val10_reg_835 <= val10_fu_296_p1;
                val11_1_reg_870 <= rij_buffer_1_q0(15 downto 8);
                val11_2_reg_898 <= rij_buffer_1_q0(23 downto 16);
                val11_reg_842 <= val11_fu_300_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_final_val_11_reg_190 <= ap_phi_reg_pp0_iter0_final_val_11_reg_190;
                ap_phi_reg_pp0_iter1_final_val_13942_reg_179 <= ap_phi_reg_pp0_iter0_final_val_13942_reg_179;
                ap_phi_reg_pp0_iter1_final_val_1_144_reg_168 <= ap_phi_reg_pp0_iter0_final_val_1_144_reg_168;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter2_final_val_11_reg_190 <= ap_phi_reg_pp0_iter1_final_val_11_reg_190;
                ap_phi_reg_pp0_iter2_final_val_13942_reg_179 <= ap_phi_reg_pp0_iter1_final_val_13942_reg_179;
                ap_phi_reg_pp0_iter2_final_val_1_144_reg_168 <= ap_phi_reg_pp0_iter1_final_val_1_144_reg_168;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter3_final_val_11_reg_190 <= ap_phi_reg_pp0_iter2_final_val_11_reg_190;
                ap_phi_reg_pp0_iter3_final_val_13942_reg_179 <= ap_phi_reg_pp0_iter2_final_val_13942_reg_179;
                ap_phi_reg_pp0_iter3_final_val_1_144_reg_168 <= ap_phi_reg_pp0_iter2_final_val_1_144_reg_168;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln40_fu_272_p2 <= std_logic_vector(unsigned(x_2_fu_84) + unsigned(ap_const_lv33_2));
    add_ln70_1_fu_478_p2 <= std_logic_vector(unsigned(zext_ln70_2_fu_462_p1) + unsigned(zext_ln70_3_fu_465_p1));
    add_ln70_2_fu_488_p2 <= std_logic_vector(unsigned(zext_ln70_5_fu_484_p1) + unsigned(zext_ln70_4_fu_474_p1));
    add_ln70_3_fu_516_p2 <= std_logic_vector(unsigned(zext_ln70_7_fu_507_p1) + unsigned(zext_ln70_6_fu_504_p1));
    add_ln70_4_fu_526_p2 <= std_logic_vector(unsigned(zext_ln70_8_fu_510_p1) + unsigned(zext_ln70_9_fu_513_p1));
    add_ln70_5_fu_536_p2 <= std_logic_vector(unsigned(zext_ln70_11_fu_532_p1) + unsigned(zext_ln70_10_fu_522_p1));
    add_ln70_6_fu_564_p2 <= std_logic_vector(unsigned(zext_ln70_13_fu_555_p1) + unsigned(zext_ln70_12_fu_552_p1));
    add_ln70_7_fu_574_p2 <= std_logic_vector(unsigned(zext_ln70_14_fu_558_p1) + unsigned(zext_ln70_15_fu_561_p1));
    add_ln70_8_fu_584_p2 <= std_logic_vector(unsigned(zext_ln70_17_fu_580_p1) + unsigned(zext_ln70_16_fu_570_p1));
    add_ln70_fu_468_p2 <= std_logic_vector(unsigned(zext_ln70_1_fu_459_p1) + unsigned(zext_ln70_fu_456_p1));
    add_ln87_fu_223_p2 <= std_logic_vector(unsigned(output_x_fu_88) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem_out_0_WREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((m_axi_gmem_out_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem_out_0_WREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((m_axi_gmem_out_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln40_fu_218_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln40_fu_218_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_phi_reg_pp0_iter0_final_val_11_reg_190 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_final_val_13942_reg_179 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_final_val_1_144_reg_168 <= "XXXXXXXX";
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    final_val_2_fu_712_p3 <= 
        min1_1_fu_696_p3 when (icmp_ln75_1_fu_706_p2(0) = '1') else 
        min2_1_fu_701_p3;
    final_val_4_fu_736_p3 <= 
        min1_2_fu_720_p3 when (icmp_ln75_2_fu_730_p2(0) = '1') else 
        min2_2_fu_725_p3;
    final_val_5_fu_616_p3 <= 
        max1_fu_600_p3 when (icmp_ln67_fu_610_p2(0) = '1') else 
        max2_fu_605_p3;
    final_val_6_fu_640_p3 <= 
        max1_1_fu_624_p3 when (icmp_ln67_1_fu_634_p2(0) = '1') else 
        max2_1_fu_629_p3;
    final_val_7_fu_664_p3 <= 
        max1_2_fu_648_p3 when (icmp_ln67_2_fu_658_p2(0) = '1') else 
        max2_2_fu_653_p3;
    final_val_fu_688_p3 <= 
        min1_fu_672_p3 when (icmp_ln75_fu_682_p2(0) = '1') else 
        min2_fu_677_p3;

    gmem_out_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem_out_0_WREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            gmem_out_blk_n_W <= m_axi_gmem_out_0_WREADY;
        else 
            gmem_out_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln40_fu_218_p2 <= "1" when (output_x_fu_88 = add_ln25_1) else "0";
    icmp_ln65_1_fu_396_p2 <= "1" when (unsigned(val00_1_fu_304_p4) > unsigned(val01_1_fu_314_p4)) else "0";
    icmp_ln65_2_fu_408_p2 <= "1" when (unsigned(val00_2_fu_344_p4) > unsigned(val01_2_fu_354_p4)) else "0";
    icmp_ln65_fu_384_p2 <= "1" when (unsigned(val00_fu_288_p1) > unsigned(val01_fu_292_p1)) else "0";
    icmp_ln66_1_fu_402_p2 <= "1" when (unsigned(val10_1_fu_324_p4) > unsigned(val11_1_fu_334_p4)) else "0";
    icmp_ln66_2_fu_414_p2 <= "1" when (unsigned(val10_2_fu_364_p4) > unsigned(val11_2_fu_374_p4)) else "0";
    icmp_ln66_fu_390_p2 <= "1" when (unsigned(val10_fu_296_p1) > unsigned(val11_fu_300_p1)) else "0";
    icmp_ln67_1_fu_634_p2 <= "1" when (unsigned(max1_1_fu_624_p3) > unsigned(max2_1_fu_629_p3)) else "0";
    icmp_ln67_2_fu_658_p2 <= "1" when (unsigned(max1_2_fu_648_p3) > unsigned(max2_2_fu_653_p3)) else "0";
    icmp_ln67_fu_610_p2 <= "1" when (unsigned(max1_fu_600_p3) > unsigned(max2_fu_605_p3)) else "0";
    icmp_ln73_1_fu_432_p2 <= "1" when (unsigned(val00_1_fu_304_p4) < unsigned(val01_1_fu_314_p4)) else "0";
    icmp_ln73_2_fu_444_p2 <= "1" when (unsigned(val00_2_fu_344_p4) < unsigned(val01_2_fu_354_p4)) else "0";
    icmp_ln73_fu_420_p2 <= "1" when (unsigned(val00_fu_288_p1) < unsigned(val01_fu_292_p1)) else "0";
    icmp_ln74_1_fu_438_p2 <= "1" when (unsigned(val10_1_fu_324_p4) < unsigned(val11_1_fu_334_p4)) else "0";
    icmp_ln74_2_fu_450_p2 <= "1" when (unsigned(val10_2_fu_364_p4) < unsigned(val11_2_fu_374_p4)) else "0";
    icmp_ln74_fu_426_p2 <= "1" when (unsigned(val10_fu_296_p1) < unsigned(val11_fu_300_p1)) else "0";
    icmp_ln75_1_fu_706_p2 <= "1" when (unsigned(min1_1_fu_696_p3) < unsigned(min2_1_fu_701_p3)) else "0";
    icmp_ln75_2_fu_730_p2 <= "1" when (unsigned(min1_2_fu_720_p3) < unsigned(min2_2_fu_725_p3)) else "0";
    icmp_ln75_fu_682_p2 <= "1" when (unsigned(min1_fu_672_p3) < unsigned(min2_fu_677_p3)) else "0";
    m_axi_gmem_out_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_out_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_out_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_out_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_out_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_out_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_out_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_out_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_out_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_out_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_out_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_out_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_out_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_out_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_out_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_out_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_out_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_out_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_out_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_out_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_out_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_out_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_out_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_out_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_out_0_BREADY <= ap_const_logic_0;
    m_axi_gmem_out_0_RREADY <= ap_const_logic_0;
        m_axi_gmem_out_0_WDATA <= std_logic_vector(IEEE.numeric_std.resize(signed(res_pixel_fu_750_p5),32));

    m_axi_gmem_out_0_WID <= ap_const_lv1_0;
    m_axi_gmem_out_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_out_0_WSTRB <= ap_const_lv4_F;
    m_axi_gmem_out_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem_out_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            m_axi_gmem_out_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_out_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    max1_1_fu_624_p3 <= 
        val00_1_reg_849 when (icmp_ln65_1_reg_915(0) = '1') else 
        val01_1_reg_856;
    max1_2_fu_648_p3 <= 
        val00_2_reg_877 when (icmp_ln65_2_reg_925(0) = '1') else 
        val01_2_reg_884;
    max1_fu_600_p3 <= 
        val00_reg_821 when (icmp_ln65_reg_905(0) = '1') else 
        val01_reg_828;
    max2_1_fu_629_p3 <= 
        val10_1_reg_863 when (icmp_ln66_1_reg_920(0) = '1') else 
        val11_1_reg_870;
    max2_2_fu_653_p3 <= 
        val10_2_reg_891 when (icmp_ln66_2_reg_930(0) = '1') else 
        val11_2_reg_898;
    max2_fu_605_p3 <= 
        val10_reg_835 when (icmp_ln66_reg_910(0) = '1') else 
        val11_reg_842;
    min1_1_fu_696_p3 <= 
        val00_1_reg_849 when (icmp_ln73_1_reg_945(0) = '1') else 
        val01_1_reg_856;
    min1_2_fu_720_p3 <= 
        val00_2_reg_877 when (icmp_ln73_2_reg_955(0) = '1') else 
        val01_2_reg_884;
    min1_fu_672_p3 <= 
        val00_reg_821 when (icmp_ln73_reg_935(0) = '1') else 
        val01_reg_828;
    min2_1_fu_701_p3 <= 
        val10_1_reg_863 when (icmp_ln74_1_reg_950(0) = '1') else 
        val11_1_reg_870;
    min2_2_fu_725_p3 <= 
        val10_2_reg_891 when (icmp_ln74_2_reg_960(0) = '1') else 
        val11_2_reg_898;
    min2_fu_677_p3 <= 
        val10_reg_835 when (icmp_ln74_reg_940(0) = '1') else 
        val11_reg_842;
    mode_read_reg_782 <= mode;
    or_ln_fu_248_p3 <= (tmp_fu_238_p4 & ap_const_lv1_1);
    res_pixel_fu_750_p5 <= (((ap_const_lv1_1 & ap_phi_reg_pp0_iter4_final_val_11_reg_190) & ap_phi_reg_pp0_iter4_final_val_1_144_reg_168) & ap_phi_reg_pp0_iter4_final_val_13942_reg_179);
    rij_buffer_0_address0 <= zext_ln45_fu_256_p1(8 - 1 downto 0);
    rij_buffer_0_address1 <= zext_ln40_fu_232_p1(8 - 1 downto 0);
    rij_buffer_0_ce0 <= rij_buffer_0_ce0_local;

    rij_buffer_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rij_buffer_0_ce0_local <= ap_const_logic_1;
        else 
            rij_buffer_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rij_buffer_0_ce1 <= rij_buffer_0_ce1_local;

    rij_buffer_0_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rij_buffer_0_ce1_local <= ap_const_logic_1;
        else 
            rij_buffer_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    rij_buffer_1_address0 <= zext_ln45_fu_256_p1(8 - 1 downto 0);
    rij_buffer_1_address1 <= zext_ln40_fu_232_p1(8 - 1 downto 0);
    rij_buffer_1_ce0 <= rij_buffer_1_ce0_local;

    rij_buffer_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rij_buffer_1_ce0_local <= ap_const_logic_1;
        else 
            rij_buffer_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    rij_buffer_1_ce1 <= rij_buffer_1_ce1_local;

    rij_buffer_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            rij_buffer_1_ce1_local <= ap_const_logic_1;
        else 
            rij_buffer_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_238_p4 <= x_2_fu_84(7 downto 1);
    val00_1_fu_304_p4 <= rij_buffer_0_q1(15 downto 8);
    val00_2_fu_344_p4 <= rij_buffer_0_q1(23 downto 16);
    val00_fu_288_p1 <= rij_buffer_0_q1(8 - 1 downto 0);
    val01_1_fu_314_p4 <= rij_buffer_0_q0(15 downto 8);
    val01_2_fu_354_p4 <= rij_buffer_0_q0(23 downto 16);
    val01_fu_292_p1 <= rij_buffer_0_q0(8 - 1 downto 0);
    val10_1_fu_324_p4 <= rij_buffer_1_q1(15 downto 8);
    val10_2_fu_364_p4 <= rij_buffer_1_q1(23 downto 16);
    val10_fu_296_p1 <= rij_buffer_1_q1(8 - 1 downto 0);
    val11_1_fu_334_p4 <= rij_buffer_1_q0(15 downto 8);
    val11_2_fu_374_p4 <= rij_buffer_1_q0(23 downto 16);
    val11_fu_300_p1 <= rij_buffer_1_q0(8 - 1 downto 0);
    zext_ln40_fu_232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_2_fu_84),64));
    zext_ln45_fu_256_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_248_p3),64));
    zext_ln70_10_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_3_fu_516_p2),10));
    zext_ln70_11_fu_532_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_4_fu_526_p2),10));
    zext_ln70_12_fu_552_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val00_2_reg_877),9));
    zext_ln70_13_fu_555_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val01_2_reg_884),9));
    zext_ln70_14_fu_558_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val10_2_reg_891),9));
    zext_ln70_15_fu_561_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val11_2_reg_898),9));
    zext_ln70_16_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_6_fu_564_p2),10));
    zext_ln70_17_fu_580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_7_fu_574_p2),10));
    zext_ln70_1_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val01_reg_828),9));
    zext_ln70_2_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val10_reg_835),9));
    zext_ln70_3_fu_465_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val11_reg_842),9));
    zext_ln70_4_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_fu_468_p2),10));
    zext_ln70_5_fu_484_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_1_fu_478_p2),10));
    zext_ln70_6_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val00_1_reg_849),9));
    zext_ln70_7_fu_507_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val01_1_reg_856),9));
    zext_ln70_8_fu_510_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val10_1_reg_863),9));
    zext_ln70_9_fu_513_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val11_1_reg_870),9));
    zext_ln70_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val00_reg_821),9));
end behav;
