# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/2EAI-HAC-2526-TaskHLS-bj-mk-tm/2D_Convolutie_VIVADO/2D_Convolutie_VIVADO.srcs/sources_1/bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_pc_1/design_1_axi_mem_intercon_imp_auto_pc_1.xci
# IP: The module: 'design_1_axi_mem_intercon_imp_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/2EAI-HAC-2526-TaskHLS-bj-mk-tm/2D_Convolutie_VIVADO/2D_Convolutie_VIVADO.gen/sources_1/bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_pc_1/design_1_axi_mem_intercon_imp_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_mem_intercon_imp_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/2EAI-HAC-2526-TaskHLS-bj-mk-tm/2D_Convolutie_VIVADO/2D_Convolutie_VIVADO.srcs/sources_1/bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_pc_1/design_1_axi_mem_intercon_imp_auto_pc_1.xci
# IP: The module: 'design_1_axi_mem_intercon_imp_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/2EAI-HAC-2526-TaskHLS-bj-mk-tm/2D_Convolutie_VIVADO/2D_Convolutie_VIVADO.gen/sources_1/bd/design_1/ip/design_1_axi_mem_intercon_imp_auto_pc_1/design_1_axi_mem_intercon_imp_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_mem_intercon_imp_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
