// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module vitis_convolution_vitis_convolution_Pipeline_Read_Rows_Read_Cols (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_in_0_AWVALID,
        m_axi_gmem_in_0_AWREADY,
        m_axi_gmem_in_0_AWADDR,
        m_axi_gmem_in_0_AWID,
        m_axi_gmem_in_0_AWLEN,
        m_axi_gmem_in_0_AWSIZE,
        m_axi_gmem_in_0_AWBURST,
        m_axi_gmem_in_0_AWLOCK,
        m_axi_gmem_in_0_AWCACHE,
        m_axi_gmem_in_0_AWPROT,
        m_axi_gmem_in_0_AWQOS,
        m_axi_gmem_in_0_AWREGION,
        m_axi_gmem_in_0_AWUSER,
        m_axi_gmem_in_0_WVALID,
        m_axi_gmem_in_0_WREADY,
        m_axi_gmem_in_0_WDATA,
        m_axi_gmem_in_0_WSTRB,
        m_axi_gmem_in_0_WLAST,
        m_axi_gmem_in_0_WID,
        m_axi_gmem_in_0_WUSER,
        m_axi_gmem_in_0_ARVALID,
        m_axi_gmem_in_0_ARREADY,
        m_axi_gmem_in_0_ARADDR,
        m_axi_gmem_in_0_ARID,
        m_axi_gmem_in_0_ARLEN,
        m_axi_gmem_in_0_ARSIZE,
        m_axi_gmem_in_0_ARBURST,
        m_axi_gmem_in_0_ARLOCK,
        m_axi_gmem_in_0_ARCACHE,
        m_axi_gmem_in_0_ARPROT,
        m_axi_gmem_in_0_ARQOS,
        m_axi_gmem_in_0_ARREGION,
        m_axi_gmem_in_0_ARUSER,
        m_axi_gmem_in_0_RVALID,
        m_axi_gmem_in_0_RREADY,
        m_axi_gmem_in_0_RDATA,
        m_axi_gmem_in_0_RLAST,
        m_axi_gmem_in_0_RID,
        m_axi_gmem_in_0_RFIFONUM,
        m_axi_gmem_in_0_RUSER,
        m_axi_gmem_in_0_RRESP,
        m_axi_gmem_in_0_BVALID,
        m_axi_gmem_in_0_BREADY,
        m_axi_gmem_in_0_BRESP,
        m_axi_gmem_in_0_BID,
        m_axi_gmem_in_0_BUSER,
        input_img,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_address0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_d0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_address0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_d0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_address0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_d0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_address0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_d0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_address0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_d0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_address0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_d0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_address0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_d0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_address0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_d0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_address0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0,
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_in_0_AWVALID;
input   m_axi_gmem_in_0_AWREADY;
output  [31:0] m_axi_gmem_in_0_AWADDR;
output  [0:0] m_axi_gmem_in_0_AWID;
output  [31:0] m_axi_gmem_in_0_AWLEN;
output  [2:0] m_axi_gmem_in_0_AWSIZE;
output  [1:0] m_axi_gmem_in_0_AWBURST;
output  [1:0] m_axi_gmem_in_0_AWLOCK;
output  [3:0] m_axi_gmem_in_0_AWCACHE;
output  [2:0] m_axi_gmem_in_0_AWPROT;
output  [3:0] m_axi_gmem_in_0_AWQOS;
output  [3:0] m_axi_gmem_in_0_AWREGION;
output  [0:0] m_axi_gmem_in_0_AWUSER;
output   m_axi_gmem_in_0_WVALID;
input   m_axi_gmem_in_0_WREADY;
output  [7:0] m_axi_gmem_in_0_WDATA;
output  [0:0] m_axi_gmem_in_0_WSTRB;
output   m_axi_gmem_in_0_WLAST;
output  [0:0] m_axi_gmem_in_0_WID;
output  [0:0] m_axi_gmem_in_0_WUSER;
output   m_axi_gmem_in_0_ARVALID;
input   m_axi_gmem_in_0_ARREADY;
output  [31:0] m_axi_gmem_in_0_ARADDR;
output  [0:0] m_axi_gmem_in_0_ARID;
output  [31:0] m_axi_gmem_in_0_ARLEN;
output  [2:0] m_axi_gmem_in_0_ARSIZE;
output  [1:0] m_axi_gmem_in_0_ARBURST;
output  [1:0] m_axi_gmem_in_0_ARLOCK;
output  [3:0] m_axi_gmem_in_0_ARCACHE;
output  [2:0] m_axi_gmem_in_0_ARPROT;
output  [3:0] m_axi_gmem_in_0_ARQOS;
output  [3:0] m_axi_gmem_in_0_ARREGION;
output  [0:0] m_axi_gmem_in_0_ARUSER;
input   m_axi_gmem_in_0_RVALID;
output   m_axi_gmem_in_0_RREADY;
input  [7:0] m_axi_gmem_in_0_RDATA;
input   m_axi_gmem_in_0_RLAST;
input  [0:0] m_axi_gmem_in_0_RID;
input  [10:0] m_axi_gmem_in_0_RFIFONUM;
input  [0:0] m_axi_gmem_in_0_RUSER;
input  [1:0] m_axi_gmem_in_0_RRESP;
input   m_axi_gmem_in_0_BVALID;
output   m_axi_gmem_in_0_BREADY;
input  [1:0] m_axi_gmem_in_0_BRESP;
input  [0:0] m_axi_gmem_in_0_BID;
input  [0:0] m_axi_gmem_in_0_BUSER;
input  [31:0] input_img;
output  [10:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_address0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0;
output  [7:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_d0;
output  [10:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_address0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0;
output  [7:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_d0;
output  [10:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_address0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0;
output  [7:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_d0;
output  [10:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_address0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0;
output  [7:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_d0;
output  [10:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_address0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0;
output  [7:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_d0;
output  [10:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_address0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0;
output  [7:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_d0;
output  [10:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_address0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0;
output  [7:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_d0;
output  [10:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_address0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0;
output  [7:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_d0;
output  [10:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_address0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0;
output   p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0;
output  [7:0] p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_d0;

reg ap_idle;
reg m_axi_gmem_in_0_ARVALID;
reg m_axi_gmem_in_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln18_fu_262_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_in_blk_n_AR;
wire    ap_block_pp0_stage0_grp1;
reg    gmem_in_blk_n_R;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] select_ln18_fu_297_p3;
reg   [7:0] select_ln18_reg_490;
wire   [7:0] select_ln18_1_fu_305_p3;
reg   [7:0] select_ln18_1_reg_496;
wire   [6:0] trunc_ln21_fu_313_p1;
reg   [6:0] trunc_ln21_reg_502;
wire   [6:0] trunc_ln21_1_fu_317_p1;
reg   [6:0] trunc_ln21_1_reg_507;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg   [6:0] tmp_1_reg_517;
reg   [6:0] tmp_1_reg_517_pp0_iter3_reg;
reg   [31:0] gmem_in_addr_reg_522;
wire   [10:0] grp_fu_452_p3;
reg   [10:0] add_ln21_2_reg_533;
reg   [10:0] add_ln21_2_reg_533_pp0_iter6_reg;
reg   [10:0] add_ln21_2_reg_533_pp0_iter7_reg;
reg   [10:0] add_ln21_2_reg_533_pp0_iter8_reg;
reg   [10:0] add_ln21_2_reg_533_pp0_iter9_reg;
reg   [10:0] add_ln21_2_reg_533_pp0_iter10_reg;
reg   [10:0] add_ln21_2_reg_533_pp0_iter11_reg;
reg   [10:0] add_ln21_2_reg_533_pp0_iter12_reg;
reg   [10:0] add_ln21_2_reg_533_pp0_iter13_reg;
reg   [7:0] gmem_in_addr_read_reg_538;
reg   [7:0] gmem_in_addr_read_reg_538_pp0_iter12_reg;
reg   [7:0] gmem_in_addr_read_reg_538_pp0_iter13_reg;
wire   [1:0] trunc_ln18_fu_423_p1;
reg   [1:0] trunc_ln18_reg_551;
wire   [1:0] trunc_ln19_fu_427_p1;
reg   [1:0] trunc_ln19_reg_555;
wire   [31:0] zext_ln21_3_fu_440_p1;
wire    ap_block_pp0_stage0_grp0;
wire   [31:0] add_ln21_1_fu_408_p2;
reg   [7:0] c_fu_90;
wire   [7:0] add_ln19_fu_321_p2;
wire    ap_loop_init;
reg   [7:0] r_fu_94;
reg   [14:0] indvar_flatten_fu_98;
wire   [14:0] add_ln18_1_fu_268_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0_local;
reg    p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0_local;
wire   [0:0] icmp_ln19_fu_291_p2;
wire   [7:0] add_ln18_fu_285_p2;
wire   [7:0] mul_ln18_fu_340_p0;
wire   [9:0] mul_ln18_fu_340_p1;
wire   [16:0] mul_ln18_fu_340_p2;
wire   [2:0] grp_fu_356_p1;
wire   [6:0] tmp_fu_346_p4;
wire   [7:0] mul_ln19_fu_368_p0;
wire   [9:0] mul_ln19_fu_368_p1;
wire   [16:0] mul_ln19_fu_368_p2;
wire   [2:0] grp_fu_384_p1;
wire   [13:0] shl_ln_fu_389_p3;
wire   [31:0] zext_ln21_fu_396_p1;
wire   [31:0] add_ln21_fu_403_p2;
wire   [31:0] zext_ln21_1_fu_400_p1;
wire   [1:0] grp_fu_356_p2;
wire   [1:0] grp_fu_384_p2;
wire   [6:0] grp_fu_452_p0;
wire   [5:0] grp_fu_452_p1;
wire   [6:0] grp_fu_452_p2;
reg    grp_fu_356_ce;
reg    grp_fu_384_ce;
reg    grp_fu_452_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [10:0] grp_fu_452_p00;
wire   [10:0] grp_fu_452_p20;
wire   [16:0] mul_ln18_fu_340_p00;
wire   [16:0] mul_ln19_fu_368_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 c_fu_90 = 8'd0;
#0 r_fu_94 = 8'd0;
#0 indvar_flatten_fu_98 = 15'd0;
#0 ap_done_reg = 1'b0;
end

vitis_convolution_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U1(
    .din0(mul_ln18_fu_340_p0),
    .din1(mul_ln18_fu_340_p1),
    .dout(mul_ln18_fu_340_p2)
);

vitis_convolution_urem_8ns_3ns_2_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_8ns_3ns_2_12_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln18_1_reg_496),
    .din1(grp_fu_356_p1),
    .ce(grp_fu_356_ce),
    .dout(grp_fu_356_p2)
);

vitis_convolution_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U3(
    .din0(mul_ln19_fu_368_p0),
    .din1(mul_ln19_fu_368_p1),
    .dout(mul_ln19_fu_368_p2)
);

vitis_convolution_urem_8ns_3ns_2_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_8ns_3ns_2_12_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln18_reg_490),
    .din1(grp_fu_384_p1),
    .ce(grp_fu_384_ce),
    .dout(grp_fu_384_p2)
);

vitis_convolution_mac_muladd_7ns_6ns_7ns_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mac_muladd_7ns_6ns_7ns_11_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_452_p0),
    .din1(grp_fu_452_p1),
    .din2(grp_fu_452_p2),
    .ce(grp_fu_452_ce),
    .dout(grp_fu_452_p3)
);

vitis_convolution_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_90 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            c_fu_90 <= add_ln19_fu_321_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln18_fu_262_p2 == 1'd0))) begin
            indvar_flatten_fu_98 <= add_ln18_1_fu_268_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_98 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        if ((ap_loop_init == 1'b1)) begin
            r_fu_94 <= 8'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            r_fu_94 <= select_ln18_1_fu_305_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        add_ln21_2_reg_533 <= grp_fu_452_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        add_ln21_2_reg_533_pp0_iter10_reg <= add_ln21_2_reg_533_pp0_iter9_reg;
        add_ln21_2_reg_533_pp0_iter11_reg <= add_ln21_2_reg_533_pp0_iter10_reg;
        add_ln21_2_reg_533_pp0_iter12_reg <= add_ln21_2_reg_533_pp0_iter11_reg;
        add_ln21_2_reg_533_pp0_iter13_reg <= add_ln21_2_reg_533_pp0_iter12_reg;
        add_ln21_2_reg_533_pp0_iter6_reg <= add_ln21_2_reg_533;
        add_ln21_2_reg_533_pp0_iter7_reg <= add_ln21_2_reg_533_pp0_iter6_reg;
        add_ln21_2_reg_533_pp0_iter8_reg <= add_ln21_2_reg_533_pp0_iter7_reg;
        add_ln21_2_reg_533_pp0_iter9_reg <= add_ln21_2_reg_533_pp0_iter8_reg;
        tmp_1_reg_517 <= {{mul_ln19_fu_368_p2[16:10]}};
        tmp_1_reg_517_pp0_iter3_reg <= tmp_1_reg_517;
        trunc_ln18_reg_551 <= trunc_ln18_fu_423_p1;
        trunc_ln19_reg_555 <= trunc_ln19_fu_427_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        gmem_in_addr_read_reg_538 <= m_axi_gmem_in_0_RDATA;
        gmem_in_addr_read_reg_538_pp0_iter12_reg <= gmem_in_addr_read_reg_538;
        gmem_in_addr_read_reg_538_pp0_iter13_reg <= gmem_in_addr_read_reg_538_pp0_iter12_reg;
        gmem_in_addr_reg_522 <= add_ln21_1_fu_408_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        select_ln18_1_reg_496 <= select_ln18_1_fu_305_p3;
        select_ln18_reg_490 <= select_ln18_fu_297_p3;
        trunc_ln21_1_reg_507 <= trunc_ln21_1_fu_317_p1;
        trunc_ln21_reg_502 <= trunc_ln21_fu_313_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln18_fu_262_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_98;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem_in_blk_n_AR = m_axi_gmem_in_0_ARREADY;
    end else begin
        gmem_in_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem_in_blk_n_R = m_axi_gmem_in_0_RVALID;
    end else begin
        gmem_in_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        grp_fu_356_ce = 1'b1;
    end else begin
        grp_fu_356_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        grp_fu_384_ce = 1'b1;
    end else begin
        grp_fu_384_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        grp_fu_452_ce = 1'b1;
    end else begin
        grp_fu_452_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem_in_0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_in_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem_in_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_in_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln19_reg_555 == 2'd0) & (trunc_ln18_reg_551 == 2'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln19_reg_555 == 2'd1) & (trunc_ln18_reg_551 == 2'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln19_reg_555 == 2'd0) & ~(trunc_ln19_reg_555 == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln18_reg_551 == 2'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln19_reg_555 == 2'd0) & (trunc_ln18_reg_551 == 2'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln19_reg_555 == 2'd1) & (trunc_ln18_reg_551 == 2'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln19_reg_555 == 2'd0) & ~(trunc_ln19_reg_555 == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln18_reg_551 == 2'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln18_reg_551 == 2'd0) & ~(trunc_ln18_reg_551 == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln19_reg_555 == 2'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln18_reg_551 == 2'd0) & ~(trunc_ln18_reg_551 == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln19_reg_555 == 2'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln18_reg_551 == 2'd0) & ~(trunc_ln19_reg_555 == 2'd0) & ~(trunc_ln19_reg_555 == 2'd1) & ~(trunc_ln18_reg_551 == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0_local = 1'b1;
    end else begin
        p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln18_1_fu_268_p2 = (ap_sig_allocacmp_indvar_flatten_load + 15'd1);

assign add_ln18_fu_285_p2 = (r_fu_94 + 8'd1);

assign add_ln19_fu_321_p2 = (select_ln18_fu_297_p3 + 8'd1);

assign add_ln21_1_fu_408_p2 = (add_ln21_fu_403_p2 + zext_ln21_1_fu_400_p1);

assign add_ln21_fu_403_p2 = (zext_ln21_fu_396_p1 + input_img);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem_in_0_RVALID == 1'b0)) | ((m_axi_gmem_in_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem_in_0_RVALID == 1'b0)) | ((m_axi_gmem_in_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter11 == 1'b1) & (m_axi_gmem_in_0_RVALID == 1'b0)) | ((m_axi_gmem_in_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign grp_fu_356_p1 = 8'd3;

assign grp_fu_384_p1 = 8'd3;

assign grp_fu_452_p0 = grp_fu_452_p00;

assign grp_fu_452_p00 = tmp_fu_346_p4;

assign grp_fu_452_p1 = 11'd43;

assign grp_fu_452_p2 = grp_fu_452_p20;

assign grp_fu_452_p20 = tmp_1_reg_517_pp0_iter3_reg;

assign icmp_ln18_fu_262_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 15'd16384) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_291_p2 = ((c_fu_90 == 8'd128) ? 1'b1 : 1'b0);

assign m_axi_gmem_in_0_ARADDR = gmem_in_addr_reg_522;

assign m_axi_gmem_in_0_ARBURST = 2'd0;

assign m_axi_gmem_in_0_ARCACHE = 4'd0;

assign m_axi_gmem_in_0_ARID = 1'd0;

assign m_axi_gmem_in_0_ARLEN = 32'd1;

assign m_axi_gmem_in_0_ARLOCK = 2'd0;

assign m_axi_gmem_in_0_ARPROT = 3'd0;

assign m_axi_gmem_in_0_ARQOS = 4'd0;

assign m_axi_gmem_in_0_ARREGION = 4'd0;

assign m_axi_gmem_in_0_ARSIZE = 3'd0;

assign m_axi_gmem_in_0_ARUSER = 1'd0;

assign m_axi_gmem_in_0_AWADDR = 32'd0;

assign m_axi_gmem_in_0_AWBURST = 2'd0;

assign m_axi_gmem_in_0_AWCACHE = 4'd0;

assign m_axi_gmem_in_0_AWID = 1'd0;

assign m_axi_gmem_in_0_AWLEN = 32'd0;

assign m_axi_gmem_in_0_AWLOCK = 2'd0;

assign m_axi_gmem_in_0_AWPROT = 3'd0;

assign m_axi_gmem_in_0_AWQOS = 4'd0;

assign m_axi_gmem_in_0_AWREGION = 4'd0;

assign m_axi_gmem_in_0_AWSIZE = 3'd0;

assign m_axi_gmem_in_0_AWUSER = 1'd0;

assign m_axi_gmem_in_0_AWVALID = 1'b0;

assign m_axi_gmem_in_0_BREADY = 1'b0;

assign m_axi_gmem_in_0_WDATA = 8'd0;

assign m_axi_gmem_in_0_WID = 1'd0;

assign m_axi_gmem_in_0_WLAST = 1'b0;

assign m_axi_gmem_in_0_WSTRB = 1'd0;

assign m_axi_gmem_in_0_WUSER = 1'd0;

assign m_axi_gmem_in_0_WVALID = 1'b0;

assign mul_ln18_fu_340_p0 = mul_ln18_fu_340_p00;

assign mul_ln18_fu_340_p00 = select_ln18_1_reg_496;

assign mul_ln18_fu_340_p1 = 17'd342;

assign mul_ln19_fu_368_p0 = mul_ln19_fu_368_p00;

assign mul_ln19_fu_368_p00 = select_ln18_reg_490;

assign mul_ln19_fu_368_p1 = 17'd342;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_address0 = zext_ln21_3_fu_440_p1;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_ce0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_d0 = gmem_in_addr_read_reg_538_pp0_iter13_reg;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_0_we0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_address0 = zext_ln21_3_fu_440_p1;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_ce0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_d0 = gmem_in_addr_read_reg_538_pp0_iter13_reg;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_1_we0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_address0 = zext_ln21_3_fu_440_p1;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_ce0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_d0 = gmem_in_addr_read_reg_538_pp0_iter13_reg;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_0_2_we0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_address0 = zext_ln21_3_fu_440_p1;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_ce0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_d0 = gmem_in_addr_read_reg_538_pp0_iter13_reg;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_0_we0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_address0 = zext_ln21_3_fu_440_p1;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_ce0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_d0 = gmem_in_addr_read_reg_538_pp0_iter13_reg;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_1_we0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_address0 = zext_ln21_3_fu_440_p1;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_ce0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_d0 = gmem_in_addr_read_reg_538_pp0_iter13_reg;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_1_2_we0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_address0 = zext_ln21_3_fu_440_p1;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_ce0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_d0 = gmem_in_addr_read_reg_538_pp0_iter13_reg;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_0_we0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_address0 = zext_ln21_3_fu_440_p1;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_ce0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_d0 = gmem_in_addr_read_reg_538_pp0_iter13_reg;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_1_we0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_address0 = zext_ln21_3_fu_440_p1;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_ce0_local;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_d0 = gmem_in_addr_read_reg_538_pp0_iter13_reg;

assign p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0 = p_ZZ17vitis_convolutionPVhPVcPA3_cE11local_input_2_2_we0_local;

assign select_ln18_1_fu_305_p3 = ((icmp_ln19_fu_291_p2[0:0] == 1'b1) ? add_ln18_fu_285_p2 : r_fu_94);

assign select_ln18_fu_297_p3 = ((icmp_ln19_fu_291_p2[0:0] == 1'b1) ? 8'd0 : c_fu_90);

assign shl_ln_fu_389_p3 = {{trunc_ln21_reg_502}, {7'd0}};

assign tmp_fu_346_p4 = {{mul_ln18_fu_340_p2[16:10]}};

assign trunc_ln18_fu_423_p1 = grp_fu_356_p2[1:0];

assign trunc_ln19_fu_427_p1 = grp_fu_384_p2[1:0];

assign trunc_ln21_1_fu_317_p1 = select_ln18_fu_297_p3[6:0];

assign trunc_ln21_fu_313_p1 = select_ln18_1_fu_305_p3[6:0];

assign zext_ln21_1_fu_400_p1 = trunc_ln21_1_reg_507;

assign zext_ln21_3_fu_440_p1 = add_ln21_2_reg_533_pp0_iter13_reg;

assign zext_ln21_fu_396_p1 = shl_ln_fu_389_p3;

endmodule //vitis_convolution_vitis_convolution_Pipeline_Read_Rows_Read_Cols
