-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity filter_afbeelding_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem_invoer_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_invoer_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_invoer_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_invoer_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_invoer_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_invoer_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_invoer_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_invoer_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_invoer_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_invoer_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_invoer_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_invoer_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_invoer_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_invoer_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_invoer_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_invoer_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_invoer_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_invoer_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_invoer_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_invoer_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_invoer_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_invoer_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_invoer_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_invoer_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_invoer_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_invoer_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_invoer_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_invoer_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_invoer_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_invoer_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_invoer_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_invoer_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_invoer_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_invoer_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_invoer_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_invoer_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_invoer_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_invoer_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_invoer_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
    m_axi_gmem_invoer_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_invoer_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_invoer_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_invoer_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_invoer_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_invoer_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_invoer_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_uitvoer_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_uitvoer_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem_uitvoer_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_uitvoer_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_uitvoer_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_uitvoer_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_uitvoer_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_uitvoer_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_uitvoer_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_uitvoer_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_uitvoer_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_uitvoer_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_uitvoer_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_uitvoer_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem_uitvoer_0_WREADY : IN STD_LOGIC;
    m_axi_gmem_uitvoer_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_uitvoer_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_uitvoer_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem_uitvoer_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_uitvoer_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_uitvoer_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_uitvoer_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem_uitvoer_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem_uitvoer_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_uitvoer_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_uitvoer_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_uitvoer_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_uitvoer_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_uitvoer_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_uitvoer_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_uitvoer_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_uitvoer_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_uitvoer_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_uitvoer_0_RVALID : IN STD_LOGIC;
    m_axi_gmem_uitvoer_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem_uitvoer_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem_uitvoer_0_RLAST : IN STD_LOGIC;
    m_axi_gmem_uitvoer_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_uitvoer_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem_uitvoer_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_uitvoer_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_uitvoer_0_BVALID : IN STD_LOGIC;
    m_axi_gmem_uitvoer_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem_uitvoer_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_uitvoer_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem_uitvoer_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    breedte : IN STD_LOGIC_VECTOR (31 downto 0);
    mul_ln3 : IN STD_LOGIC_VECTOR (61 downto 0);
    sext_ln37 : IN STD_LOGIC_VECTOR (61 downto 0);
    zext_ln37 : IN STD_LOGIC_VECTOR (31 downto 0);
    sext_ln37_1 : IN STD_LOGIC_VECTOR (32 downto 0);
    uitvoer_pixels : IN STD_LOGIC_VECTOR (63 downto 0);
    select_ln37_1 : IN STD_LOGIC_VECTOR (30 downto 0) );
end;


architecture behav of filter_afbeelding_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv62_0 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv62_1 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln37_reg_1415 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2_grp1 : BOOLEAN;
    signal first_iter_0_reg_1424 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1424_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state7_io_grp1 : BOOLEAN;
    signal and_ln63_reg_1478 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln63_reg_1478_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state8_io_grp1 : BOOLEAN;
    signal icmp_ln38_2_reg_1515 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_2_reg_1515_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state13_pp0_stage0_iter12_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln37_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem_uitvoer_blk_n_B : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal gmem_uitvoer_blk_n_AW : STD_LOGIC;
    signal gmem_uitvoer_blk_n_W : STD_LOGIC;
    signal gmem_invoer_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln37_1_cast_fu_345_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal sext_ln37_1_cast_reg_1395 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln37_cast_fu_349_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal zext_ln37_cast_reg_1400 : STD_LOGIC_VECTOR (61 downto 0);
    signal icmp_ln38_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_1410 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_reg_1415_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_reg_1415_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln37_2_fu_452_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln37_2_reg_1419 : STD_LOGIC_VECTOR (30 downto 0);
    signal first_iter_0_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1424_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_0_reg_1424_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln63_fu_476_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln63_reg_1428 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln63_reg_1428_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln63_reg_1428_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal line_buffer_addr_reg_1433 : STD_LOGIC_VECTOR (8 downto 0);
    signal addr_cmp50_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp50_reg_1438 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp50_reg_1438_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal line_buffer_1_addr_reg_1443 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln43_fu_497_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln43_reg_1449 : STD_LOGIC_VECTOR (23 downto 0);
    signal addr_cmp_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal addr_cmp_reg_1455 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln57_2_fu_520_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln57_2_reg_1460 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln57_2_reg_1460_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_reg_1466 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_reg_1466_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_reg_1472 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_reg_1472_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln63_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln63_reg_1478_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln63_reg_1478_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln63_reg_1478_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln38_fu_562_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln38_reg_1482 : STD_LOGIC_VECTOR (9 downto 0);
    signal reuse_reg46_load_reg_1492 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln57_1_fu_605_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln57_1_reg_1497 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_reg_1503 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_reg_1509 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln38_2_fu_632_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_2_reg_1515_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_2_reg_1515_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_2_reg_1515_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_2_reg_1515_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_2_reg_1515_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_2_reg_1515_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_2_reg_1515_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_341_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal mul_ln37_reg_1519 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln57_fu_670_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln57_reg_1524 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_reg_1529 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_1534 : STD_LOGIC_VECTOR (7 downto 0);
    signal sum1_fu_779_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sum1_reg_1539 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln69_fu_785_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln69_reg_1544 : STD_LOGIC_VECTOR (8 downto 0);
    signal sum3_fu_804_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sum3_reg_1549 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln70_fu_810_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln70_reg_1554 : STD_LOGIC_VECTOR (8 downto 0);
    signal sum5_fu_829_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sum5_reg_1559 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln71_fu_835_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln71_reg_1564 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln38_mid2_v_reg_1569 : STD_LOGIC_VECTOR (61 downto 0);
    signal empty_48_fu_958_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_48_reg_1574 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln80_fu_1118_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln80_reg_1579 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln80_reg_1579_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln81_fu_1144_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln81_reg_1584 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln81_reg_1584_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln82_fu_1170_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln82_reg_1589 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln82_reg_1589_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln37_2_fu_1178_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_condition_exit_pp0_iter4_stage0 : STD_LOGIC;
    signal line_buffer_1_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal line_buffer_1_q1 : STD_LOGIC_VECTOR (23 downto 0);
    signal line_buffer_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln38_1_fu_482_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal reuse_addr_reg47_fu_140 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal reuse_reg46_fu_144 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal buf_val_1_fu_588_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal reuse_addr_reg_fu_148 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal reuse_reg_fu_152 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    signal empty_fu_156 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_29_fu_160 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_30_fu_164 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_31_fu_168 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_32_fu_172 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_33_fu_176 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_34_fu_180 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_35_fu_184 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_36_fu_188 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal x_fu_192 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal y_fu_196 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal indvar_flatten_fu_200 : STD_LOGIC_VECTOR (61 downto 0) := "00000000000000000000000000000000000000000000000000000000000000";
    signal add_ln37_fu_406_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal empty_37_fu_204 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_38_fu_208 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_39_fu_212 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_40_fu_216 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_41_fu_220 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_42_fu_224 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_43_fu_228 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_44_fu_232 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal empty_45_fu_236 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal line_buffer_1_ce1_local : STD_LOGIC;
    signal line_buffer_1_we0_local : STD_LOGIC;
    signal line_buffer_1_ce0_local : STD_LOGIC;
    signal line_buffer_ce0_local : STD_LOGIC;
    signal line_buffer_we0_local : STD_LOGIC;
    signal grp_fu_341_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_341_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln38_2_fu_429_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln38_1_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln37_1_fu_446_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln37_fu_438_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_466_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_3_fu_540_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln63_1_fu_550_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln38_3_fu_629_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal buf_val_fu_664_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln70_4_fu_754_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln70_fu_721_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp1_fu_769_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp1_cast_fu_775_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln70_2_fu_733_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln70_3_fu_745_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_6_cast_fu_766_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln71_4_fu_758_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln71_fu_725_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp3_fu_794_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp3_cast_fu_800_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln71_2_fu_737_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln71_3_fu_748_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_7_cast_fu_791_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln69_4_fu_762_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln69_fu_729_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp5_fu_819_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp5_cast_fu_825_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln69_2_fu_741_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln69_3_fu_751_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_8_cast_fu_816_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln37_2_fu_925_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal sext_ln38_mid2_v_v_v_v_fu_929_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln37_3_fu_937_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln38_fu_952_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln70_1_fu_965_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln69_5_fu_974_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln69_6_fu_983_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln69_fu_977_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln71_1_fu_968_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln70_5_fu_992_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln70_6_fu_1001_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln70_fu_995_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln69_1_fu_971_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln71_5_fu_1010_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln71_6_fu_1019_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln71_fu_1013_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal som_R_fu_986_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_6_fu_1028_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal som_G_fu_1004_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_10_fu_1052_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal som_B_fu_1022_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_12_fu_1076_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln75_fu_1038_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_1044_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln80_fu_1112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln80_1_fu_1104_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln80_fu_1100_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln76_fu_1062_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_1068_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln81_fu_1138_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln81_1_fu_1130_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln81_fu_1126_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln77_fu_1086_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_1092_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln82_fu_1164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln82_1_fu_1156_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln82_fu_1152_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal uit_pixel_fu_1192_p5 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_341_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_341_p00 : STD_LOGIC_VECTOR (61 downto 0);
    signal m_axi_gmem_uitvoer_0_AWLEN0 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component filter_afbeelding_mul_31ns_32ns_62_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component filter_afbeelding_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_line_buffer_1_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (23 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component filter_afbeelding_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_line_buffer_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (23 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component filter_afbeelding_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    line_buffer_1_U : component filter_afbeelding_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_line_buffer_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 24,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => line_buffer_1_addr_reg_1443,
        ce0 => line_buffer_1_ce0_local,
        we0 => line_buffer_1_we0_local,
        d0 => trunc_ln43_reg_1449,
        address1 => line_buffer_1_address1,
        ce1 => line_buffer_1_ce1_local,
        q1 => line_buffer_1_q1);

    line_buffer_U : component filter_afbeelding_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_line_buffer_RAM_AUTO_1R1W
    generic map (
        DataWidth => 24,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => line_buffer_addr_reg_1433,
        ce0 => line_buffer_ce0_local,
        we0 => line_buffer_we0_local,
        d0 => buf_val_1_fu_588_p3,
        q0 => line_buffer_q0);

    mul_31ns_32ns_62_2_1_U1 : component filter_afbeelding_mul_31ns_32ns_62_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 31,
        din1_WIDTH => 32,
        dout_WIDTH => 62)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_341_p0,
        din1 => grp_fu_341_p1,
        ce => grp_fu_341_ce,
        dout => grp_fu_341_p2);

    flow_control_loop_pipe_sequential_init_U : component filter_afbeelding_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter4_stage0)) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_200 <= ap_const_lv62_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln37_fu_401_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_200 <= add_ln37_fu_406_p2;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg47_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_addr_reg47_fu_140 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln37_reg_1415 = ap_const_lv1_0))) then 
                    reuse_addr_reg47_fu_140 <= zext_ln38_1_fu_482_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_addr_reg_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_addr_reg_fu_148 <= ap_const_lv64_FFFFFFFFFFFFFFFF;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln37_reg_1415 = ap_const_lv1_0))) then 
                    reuse_addr_reg_fu_148 <= zext_ln38_1_fu_482_p1;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg46_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg46_fu_144 <= ap_const_lv24_0;
                elsif (((icmp_ln37_reg_1415_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    reuse_reg46_fu_144 <= buf_val_1_fu_588_p3;
                end if;
            end if; 
        end if;
    end process;

    reuse_reg_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    reuse_reg_fu_152 <= ap_const_lv24_0;
                elsif (((icmp_ln37_reg_1415_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
                    reuse_reg_fu_152 <= trunc_ln43_reg_1449;
                end if;
            end if; 
        end if;
    end process;

    x_fu_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    x_fu_192 <= ap_const_lv10_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln37_reg_1415 = ap_const_lv1_0))) then 
                    x_fu_192 <= add_ln38_fu_562_p2;
                end if;
            end if; 
        end if;
    end process;

    y_fu_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    y_fu_196 <= ap_const_lv31_0;
                elsif (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln37_reg_1415 = ap_const_lv1_0))) then 
                    y_fu_196 <= select_ln37_2_fu_452_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                add_ln38_reg_1482 <= add_ln38_fu_562_p2;
                add_ln69_reg_1544 <= add_ln69_fu_785_p2;
                add_ln70_reg_1554 <= add_ln70_fu_810_p2;
                add_ln71_reg_1564 <= add_ln71_fu_835_p2;
                addr_cmp50_reg_1438 <= addr_cmp50_fu_491_p2;
                addr_cmp50_reg_1438_pp0_iter3_reg <= addr_cmp50_reg_1438;
                addr_cmp_reg_1455 <= addr_cmp_fu_504_p2;
                and_ln63_reg_1478 <= and_ln63_fu_556_p2;
                and_ln63_reg_1478_pp0_iter3_reg <= and_ln63_reg_1478;
                and_ln63_reg_1478_pp0_iter4_reg <= and_ln63_reg_1478_pp0_iter3_reg;
                and_ln63_reg_1478_pp0_iter5_reg <= and_ln63_reg_1478_pp0_iter4_reg;
                and_ln63_reg_1478_pp0_iter6_reg <= and_ln63_reg_1478_pp0_iter5_reg;
                empty_48_reg_1574 <= empty_48_fu_958_p3;
                first_iter_0_reg_1424 <= first_iter_0_fu_460_p2;
                first_iter_0_reg_1424_pp0_iter3_reg <= first_iter_0_reg_1424;
                first_iter_0_reg_1424_pp0_iter4_reg <= first_iter_0_reg_1424_pp0_iter3_reg;
                first_iter_0_reg_1424_pp0_iter5_reg <= first_iter_0_reg_1424_pp0_iter4_reg;
                icmp_ln38_2_reg_1515 <= icmp_ln38_2_fu_632_p2;
                icmp_ln38_2_reg_1515_pp0_iter10_reg <= icmp_ln38_2_reg_1515_pp0_iter9_reg;
                icmp_ln38_2_reg_1515_pp0_iter11_reg <= icmp_ln38_2_reg_1515_pp0_iter10_reg;
                icmp_ln38_2_reg_1515_pp0_iter4_reg <= icmp_ln38_2_reg_1515;
                icmp_ln38_2_reg_1515_pp0_iter5_reg <= icmp_ln38_2_reg_1515_pp0_iter4_reg;
                icmp_ln38_2_reg_1515_pp0_iter6_reg <= icmp_ln38_2_reg_1515_pp0_iter5_reg;
                icmp_ln38_2_reg_1515_pp0_iter7_reg <= icmp_ln38_2_reg_1515_pp0_iter6_reg;
                icmp_ln38_2_reg_1515_pp0_iter8_reg <= icmp_ln38_2_reg_1515_pp0_iter7_reg;
                icmp_ln38_2_reg_1515_pp0_iter9_reg <= icmp_ln38_2_reg_1515_pp0_iter8_reg;
                icmp_ln63_reg_1428 <= icmp_ln63_fu_476_p2;
                icmp_ln63_reg_1428_pp0_iter3_reg <= icmp_ln63_reg_1428;
                icmp_ln63_reg_1428_pp0_iter4_reg <= icmp_ln63_reg_1428_pp0_iter3_reg;
                line_buffer_1_addr_reg_1443 <= zext_ln38_1_fu_482_p1(9 - 1 downto 0);
                line_buffer_addr_reg_1433 <= zext_ln38_1_fu_482_p1(9 - 1 downto 0);
                mul_ln37_reg_1519 <= grp_fu_341_p2;
                reuse_reg46_load_reg_1492 <= reuse_reg46_fu_144;
                select_ln37_2_reg_1419 <= select_ln37_2_fu_452_p3;
                select_ln80_reg_1579 <= select_ln80_fu_1118_p3;
                select_ln80_reg_1579_pp0_iter6_reg <= select_ln80_reg_1579;
                select_ln81_reg_1584 <= select_ln81_fu_1144_p3;
                select_ln81_reg_1584_pp0_iter6_reg <= select_ln81_reg_1584;
                select_ln82_reg_1589 <= select_ln82_fu_1170_p3;
                select_ln82_reg_1589_pp0_iter6_reg <= select_ln82_reg_1589;
                sext_ln38_mid2_v_reg_1569 <= add_ln37_3_fu_937_p2(63 downto 2);
                sum1_reg_1539 <= sum1_fu_779_p2;
                sum3_reg_1549 <= sum3_fu_804_p2;
                sum5_reg_1559 <= sum5_fu_829_p2;
                tmp_1_reg_1529 <= buf_val_fu_664_p3(15 downto 8);
                tmp_2_reg_1534 <= buf_val_fu_664_p3(23 downto 16);
                tmp_4_reg_1503 <= buf_val_1_fu_588_p3(15 downto 8);
                tmp_5_reg_1509 <= buf_val_1_fu_588_p3(23 downto 16);
                tmp_7_reg_1466 <= m_axi_gmem_invoer_0_RDATA(15 downto 8);
                tmp_7_reg_1466_pp0_iter3_reg <= tmp_7_reg_1466;
                tmp_8_reg_1472 <= m_axi_gmem_invoer_0_RDATA(23 downto 16);
                tmp_8_reg_1472_pp0_iter3_reg <= tmp_8_reg_1472;
                trunc_ln43_reg_1449 <= trunc_ln43_fu_497_p1;
                trunc_ln57_1_reg_1497 <= trunc_ln57_1_fu_605_p1;
                trunc_ln57_2_reg_1460 <= trunc_ln57_2_fu_520_p1;
                trunc_ln57_2_reg_1460_pp0_iter3_reg <= trunc_ln57_2_reg_1460;
                trunc_ln57_reg_1524 <= trunc_ln57_fu_670_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                icmp_ln37_reg_1415_pp0_iter2_reg <= icmp_ln37_reg_1415;
                icmp_ln37_reg_1415_pp0_iter3_reg <= icmp_ln37_reg_1415_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln37_reg_1415 <= icmp_ln37_fu_401_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln37_reg_1415_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                empty_29_fu_160 <= empty_38_fu_208;
                empty_30_fu_164 <= empty_39_fu_212;
                empty_31_fu_168 <= empty_40_fu_216;
                empty_32_fu_172 <= empty_41_fu_220;
                empty_33_fu_176 <= empty_42_fu_224;
                empty_34_fu_180 <= empty_43_fu_228;
                empty_35_fu_184 <= empty_44_fu_232;
                empty_36_fu_188 <= empty_45_fu_236;
                empty_37_fu_204 <= trunc_ln57_fu_670_p1;
                empty_38_fu_208 <= buf_val_fu_664_p3(15 downto 8);
                empty_39_fu_212 <= buf_val_fu_664_p3(23 downto 16);
                empty_40_fu_216 <= trunc_ln57_1_reg_1497;
                empty_41_fu_220 <= tmp_4_reg_1503;
                empty_42_fu_224 <= tmp_5_reg_1509;
                empty_43_fu_228 <= trunc_ln57_2_reg_1460_pp0_iter3_reg;
                empty_44_fu_232 <= tmp_7_reg_1466_pp0_iter3_reg;
                empty_45_fu_236 <= tmp_8_reg_1472_pp0_iter3_reg;
                empty_fu_156 <= empty_37_fu_204;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln38_reg_1410 <= icmp_ln38_fu_357_p2;
                sext_ln37_1_cast_reg_1395 <= sext_ln37_1_cast_fu_345_p1;
                    zext_ln37_cast_reg_1400(31 downto 0) <= zext_ln37_cast_fu_349_p1(31 downto 0);
            end if;
        end if;
    end process;
    zext_ln37_cast_reg_1400(61 downto 32) <= "000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln37_1_fu_446_p2 <= std_logic_vector(unsigned(y_fu_196) + unsigned(ap_const_lv31_1));
    add_ln37_2_fu_925_p2 <= std_logic_vector(signed(sext_ln37_1_cast_reg_1395) + signed(mul_ln37_reg_1519));
    add_ln37_3_fu_937_p2 <= std_logic_vector(unsigned(sext_ln38_mid2_v_v_v_v_fu_929_p3) + unsigned(uitvoer_pixels));
    add_ln37_fu_406_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_200) + unsigned(ap_const_lv62_1));
    add_ln38_fu_562_p2 <= std_logic_vector(unsigned(select_ln37_fu_438_p3) + unsigned(ap_const_lv10_1));
    add_ln69_fu_785_p2 <= std_logic_vector(unsigned(zext_ln70_3_fu_745_p1) + unsigned(tmp_6_cast_fu_766_p1));
    add_ln70_fu_810_p2 <= std_logic_vector(unsigned(zext_ln71_3_fu_748_p1) + unsigned(tmp_7_cast_fu_791_p1));
    add_ln71_fu_835_p2 <= std_logic_vector(unsigned(zext_ln69_3_fu_751_p1) + unsigned(tmp_8_cast_fu_816_p1));
    addr_cmp50_fu_491_p2 <= "1" when (reuse_addr_reg47_fu_140 = zext_ln38_1_fu_482_p1) else "0";
    addr_cmp_fu_504_p2 <= "1" when (reuse_addr_reg_fu_148 = zext_ln38_1_fu_482_p1) else "0";
    and_ln63_fu_556_p2 <= (icmp_ln63_fu_476_p2 and icmp_ln63_1_fu_550_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter12, ap_block_state3_pp0_stage0_iter2_grp1, ap_block_state13_pp0_stage0_iter12_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state13_pp0_stage0_iter12_grp1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter12, ap_block_state3_pp0_stage0_iter2_grp1, ap_block_state7_io_grp1, ap_block_state8_io_grp1, ap_block_state13_pp0_stage0_iter12_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state13_pp0_stage0_iter12_grp1)) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_io_grp1)) or ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_io_grp1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter12, ap_block_state3_pp0_stage0_iter2_grp1, ap_block_state7_io_grp1, ap_block_state8_io_grp1, ap_block_state13_pp0_stage0_iter12_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state13_pp0_stage0_iter12_grp1)) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_io_grp1)) or ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_io_grp1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter12, ap_block_state3_pp0_stage0_iter2_grp1, ap_block_state7_io_grp1, ap_block_state8_io_grp1, ap_block_state13_pp0_stage0_iter12_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state13_pp0_stage0_iter12_grp1)) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_io_grp1)) or ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_io_grp1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2_grp1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state13_pp0_stage0_iter12_grp1_assign_proc : process(m_axi_gmem_uitvoer_0_BVALID, icmp_ln38_2_reg_1515_pp0_iter11_reg)
    begin
                ap_block_state13_pp0_stage0_iter12_grp1 <= ((icmp_ln38_2_reg_1515_pp0_iter11_reg = ap_const_lv1_0) and (m_axi_gmem_uitvoer_0_BVALID = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_grp1_assign_proc : process(m_axi_gmem_invoer_0_RVALID, icmp_ln37_reg_1415)
    begin
                ap_block_state3_pp0_stage0_iter2_grp1 <= ((icmp_ln37_reg_1415 = ap_const_lv1_0) and (m_axi_gmem_invoer_0_RVALID = ap_const_logic_0));
    end process;


    ap_block_state7_io_grp1_assign_proc : process(m_axi_gmem_uitvoer_0_AWREADY, first_iter_0_reg_1424_pp0_iter5_reg)
    begin
                ap_block_state7_io_grp1 <= ((first_iter_0_reg_1424_pp0_iter5_reg = ap_const_lv1_1) and (m_axi_gmem_uitvoer_0_AWREADY = ap_const_logic_0));
    end process;


    ap_block_state8_io_grp1_assign_proc : process(m_axi_gmem_uitvoer_0_WREADY, and_ln63_reg_1478_pp0_iter6_reg)
    begin
                ap_block_state8_io_grp1 <= ((ap_const_lv1_1 = and_ln63_reg_1478_pp0_iter6_reg) and (m_axi_gmem_uitvoer_0_WREADY = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln37_fu_401_p2)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln37_fu_401_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter4_stage0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone, icmp_ln37_reg_1415_pp0_iter3_reg)
    begin
        if (((icmp_ln37_reg_1415_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter4_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter11_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter11_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    buf_val_1_fu_588_p3 <= 
        reuse_reg_fu_152 when (addr_cmp_reg_1455(0) = '1') else 
        line_buffer_1_q1;
    buf_val_fu_664_p3 <= 
        reuse_reg46_load_reg_1492 when (addr_cmp50_reg_1438_pp0_iter3_reg(0) = '1') else 
        line_buffer_q0;
    empty_48_fu_958_p3 <= 
        select_ln38_fu_952_p3 when (icmp_ln38_reg_1410(0) = '1') else 
        ap_const_lv31_0;
    first_iter_0_fu_460_p2 <= "1" when (select_ln37_fu_438_p3 = ap_const_lv10_0) else "0";

    gmem_invoer_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem_invoer_0_RVALID, icmp_ln37_reg_1415, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln37_reg_1415 = ap_const_lv1_0))) then 
            gmem_invoer_blk_n_R <= m_axi_gmem_invoer_0_RVALID;
        else 
            gmem_invoer_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    gmem_uitvoer_blk_n_AW_assign_proc : process(ap_enable_reg_pp0_iter6, m_axi_gmem_uitvoer_0_AWREADY, first_iter_0_reg_1424_pp0_iter5_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (first_iter_0_reg_1424_pp0_iter5_reg = ap_const_lv1_1))) then 
            gmem_uitvoer_blk_n_AW <= m_axi_gmem_uitvoer_0_AWREADY;
        else 
            gmem_uitvoer_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem_uitvoer_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter12, m_axi_gmem_uitvoer_0_BVALID, icmp_ln38_2_reg_1515_pp0_iter11_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln38_2_reg_1515_pp0_iter11_reg = ap_const_lv1_0))) then 
            gmem_uitvoer_blk_n_B <= m_axi_gmem_uitvoer_0_BVALID;
        else 
            gmem_uitvoer_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem_uitvoer_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter7, m_axi_gmem_uitvoer_0_WREADY, and_ln63_reg_1478_pp0_iter6_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_const_lv1_1 = and_ln63_reg_1478_pp0_iter6_reg))) then 
            gmem_uitvoer_blk_n_W <= m_axi_gmem_uitvoer_0_WREADY;
        else 
            gmem_uitvoer_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_341_ce_assign_proc : process(ap_block_pp0_stage0_11001_grp1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then 
            grp_fu_341_ce <= ap_const_logic_1;
        else 
            grp_fu_341_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_341_p0 <= grp_fu_341_p00(31 - 1 downto 0);
    grp_fu_341_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln37_2_reg_1419),62));
    grp_fu_341_p1 <= zext_ln37_cast_reg_1400(32 - 1 downto 0);
    icmp_ln37_fu_401_p2 <= "1" when (indvar_flatten_fu_200 = mul_ln3) else "0";
    icmp_ln38_1_fu_433_p2 <= "1" when (signed(zext_ln38_2_fu_429_p1) < signed(breedte)) else "0";
    icmp_ln38_2_fu_632_p2 <= "1" when (signed(zext_ln38_3_fu_629_p1) < signed(breedte)) else "0";
    icmp_ln38_fu_357_p2 <= "1" when (signed(breedte) > signed(ap_const_lv32_0)) else "0";
    icmp_ln63_1_fu_550_p2 <= "0" when (tmp_3_fu_540_p4 = ap_const_lv9_0) else "1";
    icmp_ln63_fu_476_p2 <= "0" when (tmp_fu_466_p4 = ap_const_lv30_0) else "1";
    icmp_ln75_fu_1038_p2 <= "1" when (signed(tmp_6_fu_1028_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln76_fu_1062_p2 <= "1" when (signed(tmp_10_fu_1052_p4) > signed(ap_const_lv3_0)) else "0";
    icmp_ln77_fu_1086_p2 <= "1" when (signed(tmp_12_fu_1076_p4) > signed(ap_const_lv3_0)) else "0";
    line_buffer_1_address1 <= zext_ln38_1_fu_482_p1(9 - 1 downto 0);

    line_buffer_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            line_buffer_1_ce0_local <= ap_const_logic_1;
        else 
            line_buffer_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            line_buffer_1_ce1_local <= ap_const_logic_1;
        else 
            line_buffer_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1, icmp_ln37_reg_1415_pp0_iter2_reg)
    begin
        if (((icmp_ln37_reg_1415_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            line_buffer_1_we0_local <= ap_const_logic_1;
        else 
            line_buffer_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1, icmp_ln37_reg_1415_pp0_iter2_reg)
    begin
        if (((icmp_ln37_reg_1415_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            line_buffer_ce0_local <= ap_const_logic_1;
        else 
            line_buffer_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    line_buffer_we0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1, icmp_ln37_reg_1415_pp0_iter2_reg)
    begin
        if (((icmp_ln37_reg_1415_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            line_buffer_we0_local <= ap_const_logic_1;
        else 
            line_buffer_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_invoer_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_invoer_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_invoer_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_invoer_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_invoer_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_invoer_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_invoer_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_invoer_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_invoer_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_invoer_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_invoer_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_invoer_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_invoer_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem_invoer_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_invoer_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_invoer_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_invoer_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem_invoer_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_invoer_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_invoer_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_invoer_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_invoer_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_invoer_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem_invoer_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem_invoer_0_BREADY <= ap_const_logic_0;

    m_axi_gmem_invoer_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln37_reg_1415, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln37_reg_1415 = ap_const_lv1_0))) then 
            m_axi_gmem_invoer_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_invoer_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_invoer_0_WDATA <= ap_const_lv32_0;
    m_axi_gmem_invoer_0_WID <= ap_const_lv1_0;
    m_axi_gmem_invoer_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_invoer_0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem_invoer_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem_invoer_0_WVALID <= ap_const_logic_0;
    m_axi_gmem_uitvoer_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem_uitvoer_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem_uitvoer_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem_uitvoer_0_ARID <= ap_const_lv1_0;
    m_axi_gmem_uitvoer_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem_uitvoer_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem_uitvoer_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem_uitvoer_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem_uitvoer_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem_uitvoer_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem_uitvoer_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem_uitvoer_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem_uitvoer_0_AWADDR <= sext_ln37_2_fu_1178_p1;
    m_axi_gmem_uitvoer_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem_uitvoer_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem_uitvoer_0_AWID <= ap_const_lv1_0;
    m_axi_gmem_uitvoer_0_AWLEN <= m_axi_gmem_uitvoer_0_AWLEN0(32 - 1 downto 0);
    m_axi_gmem_uitvoer_0_AWLEN0 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_48_reg_1574),64));
    m_axi_gmem_uitvoer_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem_uitvoer_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem_uitvoer_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem_uitvoer_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem_uitvoer_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem_uitvoer_0_AWUSER <= ap_const_lv1_0;

    m_axi_gmem_uitvoer_0_AWVALID_assign_proc : process(ap_enable_reg_pp0_iter6, first_iter_0_reg_1424_pp0_iter5_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (first_iter_0_reg_1424_pp0_iter5_reg = ap_const_lv1_1))) then 
            m_axi_gmem_uitvoer_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_uitvoer_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem_uitvoer_0_BREADY_assign_proc : process(ap_enable_reg_pp0_iter12, icmp_ln38_2_reg_1515_pp0_iter11_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln38_2_reg_1515_pp0_iter11_reg = ap_const_lv1_0))) then 
            m_axi_gmem_uitvoer_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_gmem_uitvoer_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem_uitvoer_0_RREADY <= ap_const_logic_0;
        m_axi_gmem_uitvoer_0_WDATA <= std_logic_vector(IEEE.numeric_std.resize(signed(uit_pixel_fu_1192_p5),32));

    m_axi_gmem_uitvoer_0_WID <= ap_const_lv1_0;
    m_axi_gmem_uitvoer_0_WLAST <= ap_const_logic_0;
    m_axi_gmem_uitvoer_0_WSTRB <= ap_const_lv4_F;
    m_axi_gmem_uitvoer_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem_uitvoer_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter7, and_ln63_reg_1478_pp0_iter6_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_lv1_1 = and_ln63_reg_1478_pp0_iter6_reg))) then 
            m_axi_gmem_uitvoer_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem_uitvoer_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln80_fu_1112_p2 <= (tmp_9_fu_1044_p3 or icmp_ln75_fu_1038_p2);
    or_ln81_fu_1138_p2 <= (tmp_11_fu_1068_p3 or icmp_ln76_fu_1062_p2);
    or_ln82_fu_1164_p2 <= (tmp_13_fu_1092_p3 or icmp_ln77_fu_1086_p2);
    select_ln37_2_fu_452_p3 <= 
        y_fu_196 when (icmp_ln38_1_fu_433_p2(0) = '1') else 
        add_ln37_1_fu_446_p2;
    select_ln37_fu_438_p3 <= 
        x_fu_192 when (icmp_ln38_1_fu_433_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln38_fu_952_p3 <= 
        select_ln37_1 when (icmp_ln63_reg_1428_pp0_iter4_reg(0) = '1') else 
        ap_const_lv31_0;
    select_ln80_1_fu_1104_p3 <= 
        ap_const_lv8_FF when (icmp_ln75_fu_1038_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln80_fu_1118_p3 <= 
        select_ln80_1_fu_1104_p3 when (or_ln80_fu_1112_p2(0) = '1') else 
        trunc_ln80_fu_1100_p1;
    select_ln81_1_fu_1130_p3 <= 
        ap_const_lv8_FF when (icmp_ln76_fu_1062_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln81_fu_1144_p3 <= 
        select_ln81_1_fu_1130_p3 when (or_ln81_fu_1138_p2(0) = '1') else 
        trunc_ln81_fu_1126_p1;
    select_ln82_1_fu_1156_p3 <= 
        ap_const_lv8_FF when (icmp_ln77_fu_1086_p2(0) = '1') else 
        ap_const_lv8_0;
    select_ln82_fu_1170_p3 <= 
        select_ln82_1_fu_1156_p3 when (or_ln82_fu_1164_p2(0) = '1') else 
        trunc_ln82_fu_1152_p1;
        sext_ln37_1_cast_fu_345_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln37_1),62));

        sext_ln37_2_fu_1178_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln38_mid2_v_reg_1569),64));

    sext_ln38_mid2_v_v_v_v_fu_929_p3 <= (add_ln37_2_fu_925_p2 & ap_const_lv2_0);
    som_B_fu_1022_p2 <= std_logic_vector(unsigned(zext_ln71_6_fu_1019_p1) + unsigned(sub_ln71_fu_1013_p2));
    som_G_fu_1004_p2 <= std_logic_vector(unsigned(zext_ln70_6_fu_1001_p1) + unsigned(sub_ln70_fu_995_p2));
    som_R_fu_986_p2 <= std_logic_vector(unsigned(zext_ln69_6_fu_983_p1) + unsigned(sub_ln69_fu_977_p2));
    sub_ln69_fu_977_p2 <= std_logic_vector(unsigned(zext_ln70_1_fu_965_p1) - unsigned(zext_ln69_5_fu_974_p1));
    sub_ln70_fu_995_p2 <= std_logic_vector(unsigned(zext_ln71_1_fu_968_p1) - unsigned(zext_ln70_5_fu_992_p1));
    sub_ln71_fu_1013_p2 <= std_logic_vector(unsigned(zext_ln69_1_fu_971_p1) - unsigned(zext_ln71_5_fu_1010_p1));
    sum1_fu_779_p2 <= std_logic_vector(unsigned(tmp1_cast_fu_775_p1) + unsigned(zext_ln70_2_fu_733_p1));
    sum3_fu_804_p2 <= std_logic_vector(unsigned(tmp3_cast_fu_800_p1) + unsigned(zext_ln71_2_fu_737_p1));
    sum5_fu_829_p2 <= std_logic_vector(unsigned(tmp5_cast_fu_825_p1) + unsigned(zext_ln69_2_fu_741_p1));
    tmp1_cast_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp1_fu_769_p2),10));
    tmp1_fu_769_p2 <= std_logic_vector(unsigned(zext_ln70_4_fu_754_p1) + unsigned(zext_ln70_fu_721_p1));
    tmp3_cast_fu_800_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp3_fu_794_p2),10));
    tmp3_fu_794_p2 <= std_logic_vector(unsigned(zext_ln71_4_fu_758_p1) + unsigned(zext_ln71_fu_725_p1));
    tmp5_cast_fu_825_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp5_fu_819_p2),10));
    tmp5_fu_819_p2 <= std_logic_vector(unsigned(zext_ln69_4_fu_762_p1) + unsigned(zext_ln69_fu_729_p1));
    tmp_10_fu_1052_p4 <= som_G_fu_1004_p2(10 downto 8);
    tmp_11_fu_1068_p3 <= som_G_fu_1004_p2(10 downto 10);
    tmp_12_fu_1076_p4 <= som_B_fu_1022_p2(10 downto 8);
    tmp_13_fu_1092_p3 <= som_B_fu_1022_p2(10 downto 10);
    tmp_3_fu_540_p4 <= select_ln37_fu_438_p3(9 downto 1);
    tmp_6_cast_fu_766_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln57_2_reg_1460_pp0_iter3_reg),9));
    tmp_6_fu_1028_p4 <= som_R_fu_986_p2(10 downto 8);
    tmp_7_cast_fu_791_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_reg_1466_pp0_iter3_reg),9));
    tmp_8_cast_fu_816_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_reg_1472_pp0_iter3_reg),9));
    tmp_9_fu_1044_p3 <= som_R_fu_986_p2(10 downto 10);
    tmp_fu_466_p4 <= select_ln37_2_fu_452_p3(30 downto 1);
    trunc_ln43_fu_497_p1 <= m_axi_gmem_invoer_0_RDATA(24 - 1 downto 0);
    trunc_ln57_1_fu_605_p1 <= buf_val_1_fu_588_p3(8 - 1 downto 0);
    trunc_ln57_2_fu_520_p1 <= m_axi_gmem_invoer_0_RDATA(8 - 1 downto 0);
    trunc_ln57_fu_670_p1 <= buf_val_fu_664_p3(8 - 1 downto 0);
    trunc_ln80_fu_1100_p1 <= som_R_fu_986_p2(8 - 1 downto 0);
    trunc_ln81_fu_1126_p1 <= som_G_fu_1004_p2(8 - 1 downto 0);
    trunc_ln82_fu_1152_p1 <= som_B_fu_1022_p2(8 - 1 downto 0);
    uit_pixel_fu_1192_p5 <= (((ap_const_lv1_1 & select_ln82_reg_1589_pp0_iter6_reg) & select_ln81_reg_1584_pp0_iter6_reg) & select_ln80_reg_1579_pp0_iter6_reg);
    zext_ln37_cast_fu_349_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln37),62));
    zext_ln38_1_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln37_fu_438_p3),64));
    zext_ln38_2_fu_429_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_fu_192),32));
    zext_ln38_3_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln38_reg_1482),32));
    zext_ln69_1_fu_971_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_reg_1534),11));
    zext_ln69_2_fu_741_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_33_fu_176),10));
    zext_ln69_3_fu_751_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_reg_1509),9));
    zext_ln69_4_fu_762_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_36_fu_188),9));
    zext_ln69_5_fu_974_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum1_reg_1539),11));
    zext_ln69_6_fu_983_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln69_reg_1544),11));
    zext_ln69_fu_729_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_30_fu_164),9));
    zext_ln70_1_fu_965_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln57_reg_1524),11));
    zext_ln70_2_fu_733_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_31_fu_168),10));
    zext_ln70_3_fu_745_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln57_1_reg_1497),9));
    zext_ln70_4_fu_754_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_34_fu_180),9));
    zext_ln70_5_fu_992_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum3_reg_1549),11));
    zext_ln70_6_fu_1001_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_reg_1554),11));
    zext_ln70_fu_721_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_fu_156),9));
    zext_ln71_1_fu_968_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_reg_1529),11));
    zext_ln71_2_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_32_fu_172),10));
    zext_ln71_3_fu_748_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_reg_1503),9));
    zext_ln71_4_fu_758_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_35_fu_184),9));
    zext_ln71_5_fu_1010_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum5_reg_1559),11));
    zext_ln71_6_fu_1019_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln71_reg_1564),11));
    zext_ln71_fu_725_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_29_fu_160),9));
end behav;
