-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity filter_afbeelding is
generic (
    C_M_AXI_GMEM_INVOER_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_INVOER_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_INVOER_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_INVOER_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_INVOER_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_INVOER_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_INVOER_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_INVOER_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_UITVOER_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_UITVOER_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_UITVOER_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_UITVOER_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_UITVOER_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_UITVOER_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_UITVOER_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_UITVOER_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_VITIS_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_VITIS_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_INVOER_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_INVOER_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_INVOER_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_GMEM_UITVOER_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_UITVOER_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_UITVOER_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_gmem_invoer_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_invoer_AWREADY : IN STD_LOGIC;
    m_axi_gmem_invoer_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_invoer_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_ID_WIDTH-1 downto 0);
    m_axi_gmem_invoer_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_invoer_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_invoer_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_invoer_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_invoer_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_invoer_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_invoer_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_invoer_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_invoer_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_invoer_WVALID : OUT STD_LOGIC;
    m_axi_gmem_invoer_WREADY : IN STD_LOGIC;
    m_axi_gmem_invoer_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_DATA_WIDTH-1 downto 0);
    m_axi_gmem_invoer_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_invoer_WLAST : OUT STD_LOGIC;
    m_axi_gmem_invoer_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_ID_WIDTH-1 downto 0);
    m_axi_gmem_invoer_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_invoer_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_invoer_ARREADY : IN STD_LOGIC;
    m_axi_gmem_invoer_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_invoer_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_ID_WIDTH-1 downto 0);
    m_axi_gmem_invoer_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_invoer_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_invoer_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_invoer_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_invoer_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_invoer_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_invoer_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_invoer_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_invoer_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_invoer_RVALID : IN STD_LOGIC;
    m_axi_gmem_invoer_RREADY : OUT STD_LOGIC;
    m_axi_gmem_invoer_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_DATA_WIDTH-1 downto 0);
    m_axi_gmem_invoer_RLAST : IN STD_LOGIC;
    m_axi_gmem_invoer_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_ID_WIDTH-1 downto 0);
    m_axi_gmem_invoer_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_invoer_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_invoer_BVALID : IN STD_LOGIC;
    m_axi_gmem_invoer_BREADY : OUT STD_LOGIC;
    m_axi_gmem_invoer_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_invoer_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_ID_WIDTH-1 downto 0);
    m_axi_gmem_invoer_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_INVOER_BUSER_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_uitvoer_AWREADY : IN STD_LOGIC;
    m_axi_gmem_uitvoer_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_ID_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_uitvoer_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_uitvoer_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_uitvoer_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_uitvoer_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_uitvoer_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_uitvoer_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_uitvoer_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_uitvoer_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_WVALID : OUT STD_LOGIC;
    m_axi_gmem_uitvoer_WREADY : IN STD_LOGIC;
    m_axi_gmem_uitvoer_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_DATA_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_uitvoer_WLAST : OUT STD_LOGIC;
    m_axi_gmem_uitvoer_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_ID_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_uitvoer_ARREADY : IN STD_LOGIC;
    m_axi_gmem_uitvoer_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_ID_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_uitvoer_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_uitvoer_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_uitvoer_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_uitvoer_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_uitvoer_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_uitvoer_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_uitvoer_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_uitvoer_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_RVALID : IN STD_LOGIC;
    m_axi_gmem_uitvoer_RREADY : OUT STD_LOGIC;
    m_axi_gmem_uitvoer_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_DATA_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_RLAST : IN STD_LOGIC;
    m_axi_gmem_uitvoer_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_ID_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_uitvoer_BVALID : IN STD_LOGIC;
    m_axi_gmem_uitvoer_BREADY : OUT STD_LOGIC;
    m_axi_gmem_uitvoer_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_uitvoer_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_ID_WIDTH-1 downto 0);
    m_axi_gmem_uitvoer_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_UITVOER_BUSER_WIDTH-1 downto 0);
    s_axi_vitis_control_AWVALID : IN STD_LOGIC;
    s_axi_vitis_control_AWREADY : OUT STD_LOGIC;
    s_axi_vitis_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_VITIS_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_vitis_control_WVALID : IN STD_LOGIC;
    s_axi_vitis_control_WREADY : OUT STD_LOGIC;
    s_axi_vitis_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_VITIS_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_vitis_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_VITIS_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_vitis_control_ARVALID : IN STD_LOGIC;
    s_axi_vitis_control_ARREADY : OUT STD_LOGIC;
    s_axi_vitis_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_VITIS_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_vitis_control_RVALID : OUT STD_LOGIC;
    s_axi_vitis_control_RREADY : IN STD_LOGIC;
    s_axi_vitis_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_VITIS_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_vitis_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_vitis_control_BVALID : OUT STD_LOGIC;
    s_axi_vitis_control_BREADY : IN STD_LOGIC;
    s_axi_vitis_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of filter_afbeelding is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "filter_afbeelding_filter_afbeelding,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=4053,HLS_SYN_LUT=3884,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv33_1FFFFFFFE : STD_LOGIC_VECTOR (32 downto 0) := "111111111111111111111111111111110";
    constant ap_const_lv33_0 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000000";
    constant ap_const_lv33_1 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal invoer_pixels : STD_LOGIC_VECTOR (63 downto 0);
    signal uitvoer_pixels : STD_LOGIC_VECTOR (63 downto 0);
    signal breedte : STD_LOGIC_VECTOR (31 downto 0);
    signal hoogte : STD_LOGIC_VECTOR (31 downto 0);
    signal kanalen : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_invoer_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal hoogte_read_reg_257 : STD_LOGIC_VECTOR (31 downto 0);
    signal breedte_read_reg_262 : STD_LOGIC_VECTOR (31 downto 0);
    signal uitvoer_pixels_read_reg_270 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln3_fu_139_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln3_reg_275 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln3_1_fu_143_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln3_1_reg_280 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln37_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_reg_285 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_fu_153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln38_reg_291 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_reg_297 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_135_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal mul_ln37_reg_313 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal empty_fu_183_p3 : STD_LOGIC_VECTOR (62 downto 0);
    signal empty_reg_318 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal smax_fu_190_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax_reg_323 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax12_fu_196_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax12_reg_328 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln37_3_fu_212_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal zext_ln37_1_fu_224_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln37_1_reg_353 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal select_ln37_1_fu_243_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln37_1_reg_358 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_131_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal mul_ln3_reg_363 : STD_LOGIC_VECTOR (61 downto 0);
    signal sub_ln37_fu_251_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_ln37_reg_368 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_start : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_done : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_idle : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_ready : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWVALID : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_WVALID : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_WLAST : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARVALID : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_RREADY : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_BREADY : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWVALID : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WVALID : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WLAST : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARVALID : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_RREADY : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_BREADY : STD_LOGIC;
    signal gmem_invoer_0_AWREADY : STD_LOGIC;
    signal gmem_invoer_0_WREADY : STD_LOGIC;
    signal gmem_invoer_0_ARVALID : STD_LOGIC;
    signal gmem_invoer_0_ARREADY : STD_LOGIC;
    signal gmem_invoer_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_invoer_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_invoer_0_RVALID : STD_LOGIC;
    signal gmem_invoer_0_RREADY : STD_LOGIC;
    signal gmem_invoer_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_invoer_0_RFIFONUM : STD_LOGIC_VECTOR (10 downto 0);
    signal gmem_invoer_0_BVALID : STD_LOGIC;
    signal gmem_uitvoer_0_AWVALID : STD_LOGIC;
    signal gmem_uitvoer_0_AWREADY : STD_LOGIC;
    signal gmem_uitvoer_0_WVALID : STD_LOGIC;
    signal gmem_uitvoer_0_WREADY : STD_LOGIC;
    signal gmem_uitvoer_0_ARREADY : STD_LOGIC;
    signal gmem_uitvoer_0_RVALID : STD_LOGIC;
    signal gmem_uitvoer_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_uitvoer_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_uitvoer_0_BVALID : STD_LOGIC;
    signal gmem_uitvoer_0_BREADY : STD_LOGIC;
    signal grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal sext_ln37_fu_202_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_131_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_131_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_135_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_135_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln37_fu_177_p3 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln37_fu_227_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal icmp_ln37_1_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln37_fu_233_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal grp_fu_131_p00 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_fu_131_p10 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_fu_135_p00 : STD_LOGIC_VECTOR (62 downto 0);
    signal grp_fu_135_p10 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component filter_afbeelding_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_invoer_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_invoer_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_invoer_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_invoer_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_invoer_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_invoer_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_invoer_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_invoer_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_invoer_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_invoer_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_invoer_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_invoer_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_invoer_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_invoer_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_invoer_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_invoer_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_invoer_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_invoer_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_invoer_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_invoer_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_invoer_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_invoer_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_invoer_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_invoer_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_invoer_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_invoer_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_invoer_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_invoer_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_invoer_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_invoer_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_invoer_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_invoer_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_invoer_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_invoer_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_invoer_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_invoer_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_invoer_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_invoer_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_invoer_0_RFIFONUM : IN STD_LOGIC_VECTOR (10 downto 0);
        m_axi_gmem_invoer_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_invoer_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_invoer_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_invoer_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_invoer_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_invoer_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_invoer_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_uitvoer_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_uitvoer_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_uitvoer_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_uitvoer_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_uitvoer_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_uitvoer_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_uitvoer_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_uitvoer_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_uitvoer_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_uitvoer_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_uitvoer_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_uitvoer_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_uitvoer_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_uitvoer_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_uitvoer_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_uitvoer_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_uitvoer_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_uitvoer_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_uitvoer_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_uitvoer_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_uitvoer_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_uitvoer_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_uitvoer_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_uitvoer_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_uitvoer_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_uitvoer_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_uitvoer_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_uitvoer_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_uitvoer_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_uitvoer_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_uitvoer_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_uitvoer_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_uitvoer_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_uitvoer_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_uitvoer_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_uitvoer_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_uitvoer_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_uitvoer_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_uitvoer_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_uitvoer_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_uitvoer_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_uitvoer_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_uitvoer_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_uitvoer_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_uitvoer_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_uitvoer_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        breedte : IN STD_LOGIC_VECTOR (31 downto 0);
        mul_ln3 : IN STD_LOGIC_VECTOR (61 downto 0);
        sext_ln37 : IN STD_LOGIC_VECTOR (61 downto 0);
        zext_ln37 : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln37_1 : IN STD_LOGIC_VECTOR (32 downto 0);
        uitvoer_pixels : IN STD_LOGIC_VECTOR (63 downto 0);
        select_ln37_1 : IN STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component filter_afbeelding_mul_31ns_31ns_62_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (30 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component filter_afbeelding_mul_32ns_32ns_63_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (62 downto 0) );
    end component;


    component filter_afbeelding_vitis_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        invoer_pixels : OUT STD_LOGIC_VECTOR (63 downto 0);
        uitvoer_pixels : OUT STD_LOGIC_VECTOR (63 downto 0);
        breedte : OUT STD_LOGIC_VECTOR (31 downto 0);
        hoogte : OUT STD_LOGIC_VECTOR (31 downto 0);
        kanalen : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component filter_afbeelding_gmem_invoer_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (10 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;


    component filter_afbeelding_gmem_uitvoer_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116 : component filter_afbeelding_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_start,
        ap_done => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_done,
        ap_idle => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_idle,
        ap_ready => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_ready,
        m_axi_gmem_invoer_0_AWVALID => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWVALID,
        m_axi_gmem_invoer_0_AWREADY => ap_const_logic_0,
        m_axi_gmem_invoer_0_AWADDR => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWADDR,
        m_axi_gmem_invoer_0_AWID => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWID,
        m_axi_gmem_invoer_0_AWLEN => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWLEN,
        m_axi_gmem_invoer_0_AWSIZE => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWSIZE,
        m_axi_gmem_invoer_0_AWBURST => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWBURST,
        m_axi_gmem_invoer_0_AWLOCK => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWLOCK,
        m_axi_gmem_invoer_0_AWCACHE => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWCACHE,
        m_axi_gmem_invoer_0_AWPROT => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWPROT,
        m_axi_gmem_invoer_0_AWQOS => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWQOS,
        m_axi_gmem_invoer_0_AWREGION => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWREGION,
        m_axi_gmem_invoer_0_AWUSER => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_AWUSER,
        m_axi_gmem_invoer_0_WVALID => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_WVALID,
        m_axi_gmem_invoer_0_WREADY => ap_const_logic_0,
        m_axi_gmem_invoer_0_WDATA => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_WDATA,
        m_axi_gmem_invoer_0_WSTRB => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_WSTRB,
        m_axi_gmem_invoer_0_WLAST => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_WLAST,
        m_axi_gmem_invoer_0_WID => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_WID,
        m_axi_gmem_invoer_0_WUSER => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_WUSER,
        m_axi_gmem_invoer_0_ARVALID => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARVALID,
        m_axi_gmem_invoer_0_ARREADY => gmem_invoer_0_ARREADY,
        m_axi_gmem_invoer_0_ARADDR => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARADDR,
        m_axi_gmem_invoer_0_ARID => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARID,
        m_axi_gmem_invoer_0_ARLEN => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARLEN,
        m_axi_gmem_invoer_0_ARSIZE => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARSIZE,
        m_axi_gmem_invoer_0_ARBURST => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARBURST,
        m_axi_gmem_invoer_0_ARLOCK => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARLOCK,
        m_axi_gmem_invoer_0_ARCACHE => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARCACHE,
        m_axi_gmem_invoer_0_ARPROT => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARPROT,
        m_axi_gmem_invoer_0_ARQOS => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARQOS,
        m_axi_gmem_invoer_0_ARREGION => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARREGION,
        m_axi_gmem_invoer_0_ARUSER => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARUSER,
        m_axi_gmem_invoer_0_RVALID => gmem_invoer_0_RVALID,
        m_axi_gmem_invoer_0_RREADY => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_RREADY,
        m_axi_gmem_invoer_0_RDATA => gmem_invoer_0_RDATA,
        m_axi_gmem_invoer_0_RLAST => ap_const_logic_0,
        m_axi_gmem_invoer_0_RID => ap_const_lv1_0,
        m_axi_gmem_invoer_0_RFIFONUM => gmem_invoer_0_RFIFONUM,
        m_axi_gmem_invoer_0_RUSER => ap_const_lv1_0,
        m_axi_gmem_invoer_0_RRESP => ap_const_lv2_0,
        m_axi_gmem_invoer_0_BVALID => ap_const_logic_0,
        m_axi_gmem_invoer_0_BREADY => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_BREADY,
        m_axi_gmem_invoer_0_BRESP => ap_const_lv2_0,
        m_axi_gmem_invoer_0_BID => ap_const_lv1_0,
        m_axi_gmem_invoer_0_BUSER => ap_const_lv1_0,
        m_axi_gmem_uitvoer_0_AWVALID => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWVALID,
        m_axi_gmem_uitvoer_0_AWREADY => gmem_uitvoer_0_AWREADY,
        m_axi_gmem_uitvoer_0_AWADDR => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWADDR,
        m_axi_gmem_uitvoer_0_AWID => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWID,
        m_axi_gmem_uitvoer_0_AWLEN => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWLEN,
        m_axi_gmem_uitvoer_0_AWSIZE => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWSIZE,
        m_axi_gmem_uitvoer_0_AWBURST => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWBURST,
        m_axi_gmem_uitvoer_0_AWLOCK => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWLOCK,
        m_axi_gmem_uitvoer_0_AWCACHE => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWCACHE,
        m_axi_gmem_uitvoer_0_AWPROT => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWPROT,
        m_axi_gmem_uitvoer_0_AWQOS => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWQOS,
        m_axi_gmem_uitvoer_0_AWREGION => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWREGION,
        m_axi_gmem_uitvoer_0_AWUSER => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWUSER,
        m_axi_gmem_uitvoer_0_WVALID => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WVALID,
        m_axi_gmem_uitvoer_0_WREADY => gmem_uitvoer_0_WREADY,
        m_axi_gmem_uitvoer_0_WDATA => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WDATA,
        m_axi_gmem_uitvoer_0_WSTRB => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WSTRB,
        m_axi_gmem_uitvoer_0_WLAST => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WLAST,
        m_axi_gmem_uitvoer_0_WID => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WID,
        m_axi_gmem_uitvoer_0_WUSER => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WUSER,
        m_axi_gmem_uitvoer_0_ARVALID => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARVALID,
        m_axi_gmem_uitvoer_0_ARREADY => ap_const_logic_0,
        m_axi_gmem_uitvoer_0_ARADDR => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARADDR,
        m_axi_gmem_uitvoer_0_ARID => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARID,
        m_axi_gmem_uitvoer_0_ARLEN => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARLEN,
        m_axi_gmem_uitvoer_0_ARSIZE => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARSIZE,
        m_axi_gmem_uitvoer_0_ARBURST => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARBURST,
        m_axi_gmem_uitvoer_0_ARLOCK => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARLOCK,
        m_axi_gmem_uitvoer_0_ARCACHE => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARCACHE,
        m_axi_gmem_uitvoer_0_ARPROT => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARPROT,
        m_axi_gmem_uitvoer_0_ARQOS => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARQOS,
        m_axi_gmem_uitvoer_0_ARREGION => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARREGION,
        m_axi_gmem_uitvoer_0_ARUSER => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_ARUSER,
        m_axi_gmem_uitvoer_0_RVALID => ap_const_logic_0,
        m_axi_gmem_uitvoer_0_RREADY => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_RREADY,
        m_axi_gmem_uitvoer_0_RDATA => ap_const_lv32_0,
        m_axi_gmem_uitvoer_0_RLAST => ap_const_logic_0,
        m_axi_gmem_uitvoer_0_RID => ap_const_lv1_0,
        m_axi_gmem_uitvoer_0_RFIFONUM => ap_const_lv9_0,
        m_axi_gmem_uitvoer_0_RUSER => ap_const_lv1_0,
        m_axi_gmem_uitvoer_0_RRESP => ap_const_lv2_0,
        m_axi_gmem_uitvoer_0_BVALID => gmem_uitvoer_0_BVALID,
        m_axi_gmem_uitvoer_0_BREADY => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_BREADY,
        m_axi_gmem_uitvoer_0_BRESP => ap_const_lv2_0,
        m_axi_gmem_uitvoer_0_BID => ap_const_lv1_0,
        m_axi_gmem_uitvoer_0_BUSER => ap_const_lv1_0,
        breedte => breedte_read_reg_262,
        mul_ln3 => mul_ln3_reg_363,
        sext_ln37 => trunc_ln_reg_297,
        zext_ln37 => breedte_read_reg_262,
        sext_ln37_1 => sub_ln37_reg_368,
        uitvoer_pixels => uitvoer_pixels_read_reg_270,
        select_ln37_1 => select_ln37_1_reg_358);

    vitis_control_s_axi_U : component filter_afbeelding_vitis_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_VITIS_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_VITIS_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_vitis_control_AWVALID,
        AWREADY => s_axi_vitis_control_AWREADY,
        AWADDR => s_axi_vitis_control_AWADDR,
        WVALID => s_axi_vitis_control_WVALID,
        WREADY => s_axi_vitis_control_WREADY,
        WDATA => s_axi_vitis_control_WDATA,
        WSTRB => s_axi_vitis_control_WSTRB,
        ARVALID => s_axi_vitis_control_ARVALID,
        ARREADY => s_axi_vitis_control_ARREADY,
        ARADDR => s_axi_vitis_control_ARADDR,
        RVALID => s_axi_vitis_control_RVALID,
        RREADY => s_axi_vitis_control_RREADY,
        RDATA => s_axi_vitis_control_RDATA,
        RRESP => s_axi_vitis_control_RRESP,
        BVALID => s_axi_vitis_control_BVALID,
        BREADY => s_axi_vitis_control_BREADY,
        BRESP => s_axi_vitis_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        invoer_pixels => invoer_pixels,
        uitvoer_pixels => uitvoer_pixels,
        breedte => breedte,
        hoogte => hoogte,
        kanalen => kanalen,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    gmem_invoer_m_axi_U : component filter_afbeelding_gmem_invoer_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 64,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_INVOER_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_INVOER_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_INVOER_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_INVOER_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_INVOER_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_INVOER_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_INVOER_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_INVOER_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_INVOER_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_INVOER_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_INVOER_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 16,
        CH0_NUM_WRITE_OUTSTANDING => 16,
        CH0_USER_RFIFONUM_WIDTH => 11,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_gmem_invoer_AWVALID,
        AWREADY => m_axi_gmem_invoer_AWREADY,
        AWADDR => m_axi_gmem_invoer_AWADDR,
        AWID => m_axi_gmem_invoer_AWID,
        AWLEN => m_axi_gmem_invoer_AWLEN,
        AWSIZE => m_axi_gmem_invoer_AWSIZE,
        AWBURST => m_axi_gmem_invoer_AWBURST,
        AWLOCK => m_axi_gmem_invoer_AWLOCK,
        AWCACHE => m_axi_gmem_invoer_AWCACHE,
        AWPROT => m_axi_gmem_invoer_AWPROT,
        AWQOS => m_axi_gmem_invoer_AWQOS,
        AWREGION => m_axi_gmem_invoer_AWREGION,
        AWUSER => m_axi_gmem_invoer_AWUSER,
        WVALID => m_axi_gmem_invoer_WVALID,
        WREADY => m_axi_gmem_invoer_WREADY,
        WDATA => m_axi_gmem_invoer_WDATA,
        WSTRB => m_axi_gmem_invoer_WSTRB,
        WLAST => m_axi_gmem_invoer_WLAST,
        WID => m_axi_gmem_invoer_WID,
        WUSER => m_axi_gmem_invoer_WUSER,
        ARVALID => m_axi_gmem_invoer_ARVALID,
        ARREADY => m_axi_gmem_invoer_ARREADY,
        ARADDR => m_axi_gmem_invoer_ARADDR,
        ARID => m_axi_gmem_invoer_ARID,
        ARLEN => m_axi_gmem_invoer_ARLEN,
        ARSIZE => m_axi_gmem_invoer_ARSIZE,
        ARBURST => m_axi_gmem_invoer_ARBURST,
        ARLOCK => m_axi_gmem_invoer_ARLOCK,
        ARCACHE => m_axi_gmem_invoer_ARCACHE,
        ARPROT => m_axi_gmem_invoer_ARPROT,
        ARQOS => m_axi_gmem_invoer_ARQOS,
        ARREGION => m_axi_gmem_invoer_ARREGION,
        ARUSER => m_axi_gmem_invoer_ARUSER,
        RVALID => m_axi_gmem_invoer_RVALID,
        RREADY => m_axi_gmem_invoer_RREADY,
        RDATA => m_axi_gmem_invoer_RDATA,
        RLAST => m_axi_gmem_invoer_RLAST,
        RID => m_axi_gmem_invoer_RID,
        RUSER => m_axi_gmem_invoer_RUSER,
        RRESP => m_axi_gmem_invoer_RRESP,
        BVALID => m_axi_gmem_invoer_BVALID,
        BREADY => m_axi_gmem_invoer_BREADY,
        BRESP => m_axi_gmem_invoer_BRESP,
        BID => m_axi_gmem_invoer_BID,
        BUSER => m_axi_gmem_invoer_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => gmem_invoer_0_ARVALID,
        I_CH0_ARREADY => gmem_invoer_0_ARREADY,
        I_CH0_ARADDR => gmem_invoer_0_ARADDR,
        I_CH0_ARLEN => gmem_invoer_0_ARLEN,
        I_CH0_RVALID => gmem_invoer_0_RVALID,
        I_CH0_RREADY => gmem_invoer_0_RREADY,
        I_CH0_RDATA => gmem_invoer_0_RDATA,
        I_CH0_RFIFONUM => gmem_invoer_0_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => gmem_invoer_0_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => gmem_invoer_0_WREADY,
        I_CH0_WDATA => ap_const_lv32_0,
        I_CH0_WSTRB => ap_const_lv4_0,
        I_CH0_BVALID => gmem_invoer_0_BVALID,
        I_CH0_BREADY => ap_const_logic_0);

    gmem_uitvoer_m_axi_U : component filter_afbeelding_gmem_uitvoer_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 4,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 64,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_UITVOER_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_UITVOER_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_UITVOER_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_UITVOER_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_UITVOER_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_UITVOER_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_UITVOER_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_UITVOER_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_UITVOER_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_UITVOER_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_UITVOER_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 16,
        CH0_NUM_WRITE_OUTSTANDING => 16,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 0,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_gmem_uitvoer_AWVALID,
        AWREADY => m_axi_gmem_uitvoer_AWREADY,
        AWADDR => m_axi_gmem_uitvoer_AWADDR,
        AWID => m_axi_gmem_uitvoer_AWID,
        AWLEN => m_axi_gmem_uitvoer_AWLEN,
        AWSIZE => m_axi_gmem_uitvoer_AWSIZE,
        AWBURST => m_axi_gmem_uitvoer_AWBURST,
        AWLOCK => m_axi_gmem_uitvoer_AWLOCK,
        AWCACHE => m_axi_gmem_uitvoer_AWCACHE,
        AWPROT => m_axi_gmem_uitvoer_AWPROT,
        AWQOS => m_axi_gmem_uitvoer_AWQOS,
        AWREGION => m_axi_gmem_uitvoer_AWREGION,
        AWUSER => m_axi_gmem_uitvoer_AWUSER,
        WVALID => m_axi_gmem_uitvoer_WVALID,
        WREADY => m_axi_gmem_uitvoer_WREADY,
        WDATA => m_axi_gmem_uitvoer_WDATA,
        WSTRB => m_axi_gmem_uitvoer_WSTRB,
        WLAST => m_axi_gmem_uitvoer_WLAST,
        WID => m_axi_gmem_uitvoer_WID,
        WUSER => m_axi_gmem_uitvoer_WUSER,
        ARVALID => m_axi_gmem_uitvoer_ARVALID,
        ARREADY => m_axi_gmem_uitvoer_ARREADY,
        ARADDR => m_axi_gmem_uitvoer_ARADDR,
        ARID => m_axi_gmem_uitvoer_ARID,
        ARLEN => m_axi_gmem_uitvoer_ARLEN,
        ARSIZE => m_axi_gmem_uitvoer_ARSIZE,
        ARBURST => m_axi_gmem_uitvoer_ARBURST,
        ARLOCK => m_axi_gmem_uitvoer_ARLOCK,
        ARCACHE => m_axi_gmem_uitvoer_ARCACHE,
        ARPROT => m_axi_gmem_uitvoer_ARPROT,
        ARQOS => m_axi_gmem_uitvoer_ARQOS,
        ARREGION => m_axi_gmem_uitvoer_ARREGION,
        ARUSER => m_axi_gmem_uitvoer_ARUSER,
        RVALID => m_axi_gmem_uitvoer_RVALID,
        RREADY => m_axi_gmem_uitvoer_RREADY,
        RDATA => m_axi_gmem_uitvoer_RDATA,
        RLAST => m_axi_gmem_uitvoer_RLAST,
        RID => m_axi_gmem_uitvoer_RID,
        RUSER => m_axi_gmem_uitvoer_RUSER,
        RRESP => m_axi_gmem_uitvoer_RRESP,
        BVALID => m_axi_gmem_uitvoer_BVALID,
        BREADY => m_axi_gmem_uitvoer_BREADY,
        BRESP => m_axi_gmem_uitvoer_BRESP,
        BID => m_axi_gmem_uitvoer_BID,
        BUSER => m_axi_gmem_uitvoer_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => ap_const_logic_0,
        I_CH0_ARREADY => gmem_uitvoer_0_ARREADY,
        I_CH0_ARADDR => ap_const_lv64_0,
        I_CH0_ARLEN => ap_const_lv32_0,
        I_CH0_RVALID => gmem_uitvoer_0_RVALID,
        I_CH0_RREADY => ap_const_logic_0,
        I_CH0_RDATA => gmem_uitvoer_0_RDATA,
        I_CH0_RFIFONUM => gmem_uitvoer_0_RFIFONUM,
        I_CH0_AWVALID => gmem_uitvoer_0_AWVALID,
        I_CH0_AWREADY => gmem_uitvoer_0_AWREADY,
        I_CH0_AWADDR => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWADDR,
        I_CH0_AWLEN => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWLEN,
        I_CH0_WVALID => gmem_uitvoer_0_WVALID,
        I_CH0_WREADY => gmem_uitvoer_0_WREADY,
        I_CH0_WDATA => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WDATA,
        I_CH0_WSTRB => grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WSTRB,
        I_CH0_BVALID => gmem_uitvoer_0_BVALID,
        I_CH0_BREADY => gmem_uitvoer_0_BREADY);

    mul_31ns_31ns_62_2_1_U14 : component filter_afbeelding_mul_31ns_31ns_62_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        dout_WIDTH => 62)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_131_p0,
        din1 => grp_fu_131_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_131_p2);

    mul_32ns_32ns_63_2_1_U15 : component filter_afbeelding_mul_32ns_32ns_63_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 63)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_135_p0,
        din1 => grp_fu_135_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_135_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_ready = ap_const_logic_1)) then 
                    grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                breedte_read_reg_262 <= breedte;
                hoogte_read_reg_257 <= hoogte;
                icmp_ln37_reg_285 <= icmp_ln37_fu_147_p2;
                icmp_ln38_reg_291 <= icmp_ln38_fu_153_p2;
                trunc_ln3_1_reg_280 <= trunc_ln3_1_fu_143_p1;
                trunc_ln3_reg_275 <= trunc_ln3_fu_139_p1;
                trunc_ln_reg_297 <= invoer_pixels(63 downto 2);
                uitvoer_pixels_read_reg_270 <= uitvoer_pixels;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                empty_reg_318 <= empty_fu_183_p3;
                smax12_reg_328 <= smax12_fu_196_p3;
                smax_reg_323 <= smax_fu_190_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                mul_ln37_reg_313 <= grp_fu_135_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                mul_ln3_reg_363 <= grp_fu_131_p2;
                select_ln37_1_reg_358 <= select_ln37_1_fu_243_p3;
                    zext_ln37_1_reg_353(31 downto 0) <= zext_ln37_1_fu_224_p1(31 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                sub_ln37_reg_368 <= sub_ln37_fu_251_p2;
            end if;
        end if;
    end process;
    zext_ln37_1_reg_353(32) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state5, grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_done, gmem_invoer_0_ARREADY, ap_CS_fsm_state14)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((gmem_invoer_0_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                if (((grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln37_fu_227_p2 <= std_logic_vector(unsigned(zext_ln37_1_fu_224_p1) + unsigned(ap_const_lv33_1FFFFFFFE));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state14_blk_assign_proc : process(grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_done)
    begin
        if ((grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(gmem_invoer_0_ARREADY)
    begin
        if ((gmem_invoer_0_ARREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_done, ap_CS_fsm_state14)
    begin
        if (((grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_done, ap_CS_fsm_state14)
    begin
        if (((grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    empty_fu_183_p3 <= 
        select_ln37_fu_177_p3 when (icmp_ln37_reg_285(0) = '1') else 
        ap_const_lv63_0;

    gmem_invoer_0_ARADDR_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state13, grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARADDR, gmem_invoer_0_ARREADY, ap_CS_fsm_state14, sext_ln37_fu_202_p1)
    begin
        if (((gmem_invoer_0_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            gmem_invoer_0_ARADDR <= sext_ln37_fu_202_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            gmem_invoer_0_ARADDR <= grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARADDR;
        else 
            gmem_invoer_0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    gmem_invoer_0_ARLEN_assign_proc : process(ap_CS_fsm_state5, zext_ln37_3_fu_212_p1, ap_CS_fsm_state13, grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARLEN, gmem_invoer_0_ARREADY, ap_CS_fsm_state14)
    begin
        if (((gmem_invoer_0_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            gmem_invoer_0_ARLEN <= zext_ln37_3_fu_212_p1(32 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            gmem_invoer_0_ARLEN <= grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARLEN;
        else 
            gmem_invoer_0_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    gmem_invoer_0_ARVALID_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state13, grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARVALID, gmem_invoer_0_ARREADY, ap_CS_fsm_state14)
    begin
        if (((gmem_invoer_0_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            gmem_invoer_0_ARVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            gmem_invoer_0_ARVALID <= grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_ARVALID;
        else 
            gmem_invoer_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_invoer_0_RREADY_assign_proc : process(ap_CS_fsm_state13, grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_RREADY, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            gmem_invoer_0_RREADY <= grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_invoer_0_RREADY;
        else 
            gmem_invoer_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_invoer_blk_n_AR_assign_proc : process(m_axi_gmem_invoer_ARREADY, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            gmem_invoer_blk_n_AR <= m_axi_gmem_invoer_ARREADY;
        else 
            gmem_invoer_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem_uitvoer_0_AWVALID_assign_proc : process(ap_CS_fsm_state13, grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWVALID, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            gmem_uitvoer_0_AWVALID <= grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_AWVALID;
        else 
            gmem_uitvoer_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_uitvoer_0_BREADY_assign_proc : process(ap_CS_fsm_state13, grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_BREADY, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            gmem_uitvoer_0_BREADY <= grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_BREADY;
        else 
            gmem_uitvoer_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_uitvoer_0_WVALID_assign_proc : process(ap_CS_fsm_state13, grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WVALID, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            gmem_uitvoer_0_WVALID <= grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_m_axi_gmem_uitvoer_0_WVALID;
        else 
            gmem_uitvoer_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_start <= grp_filter_afbeelding_Pipeline_Loop_Rows_Loop_Cols_fu_116_ap_start_reg;
    grp_fu_131_p0 <= grp_fu_131_p00(31 - 1 downto 0);
    grp_fu_131_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax_reg_323),62));
    grp_fu_131_p1 <= grp_fu_131_p10(31 - 1 downto 0);
    grp_fu_131_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax12_reg_328),62));
    grp_fu_135_p0 <= grp_fu_135_p00(32 - 1 downto 0);
    grp_fu_135_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hoogte_read_reg_257),63));
    grp_fu_135_p1 <= grp_fu_135_p10(32 - 1 downto 0);
    grp_fu_135_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(breedte_read_reg_262),63));
    icmp_ln37_1_fu_237_p2 <= "1" when (signed(add_ln37_fu_227_p2) > signed(ap_const_lv33_0)) else "0";
    icmp_ln37_fu_147_p2 <= "1" when (signed(hoogte) > signed(ap_const_lv32_0)) else "0";
    icmp_ln38_fu_153_p2 <= "1" when (signed(breedte) > signed(ap_const_lv32_0)) else "0";
    select_ln37_1_fu_243_p3 <= 
        trunc_ln37_fu_233_p1 when (icmp_ln37_1_fu_237_p2(0) = '1') else 
        ap_const_lv31_0;
    select_ln37_fu_177_p3 <= 
        mul_ln37_reg_313 when (icmp_ln38_reg_291(0) = '1') else 
        ap_const_lv63_0;
        sext_ln37_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_297),64));

    smax12_fu_196_p3 <= 
        trunc_ln3_reg_275 when (icmp_ln38_reg_291(0) = '1') else 
        ap_const_lv31_0;
    smax_fu_190_p3 <= 
        trunc_ln3_1_reg_280 when (icmp_ln37_reg_285(0) = '1') else 
        ap_const_lv31_0;
    sub_ln37_fu_251_p2 <= std_logic_vector(unsigned(ap_const_lv33_1) - unsigned(zext_ln37_1_reg_353));
    trunc_ln37_fu_233_p1 <= add_ln37_fu_227_p2(31 - 1 downto 0);
    trunc_ln3_1_fu_143_p1 <= hoogte(31 - 1 downto 0);
    trunc_ln3_fu_139_p1 <= breedte(31 - 1 downto 0);
    zext_ln37_1_fu_224_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(breedte_read_reg_262),33));
    zext_ln37_3_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_reg_318),64));
end behav;
