-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.2 (win64) Build 6299465 Fri Nov 14 19:35:11 GMT 2025
-- Date        : Sat May 23 03:43:42 2026
-- Host        : ELITE running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ design_1_filter_afbeelding_0_0_stub.vhdl
-- Design      : design_1_filter_afbeelding_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg400-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    s_axi_vitis_control_ARADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_vitis_control_ARREADY : out STD_LOGIC;
    s_axi_vitis_control_ARVALID : in STD_LOGIC;
    s_axi_vitis_control_AWADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_vitis_control_AWREADY : out STD_LOGIC;
    s_axi_vitis_control_AWVALID : in STD_LOGIC;
    s_axi_vitis_control_BREADY : in STD_LOGIC;
    s_axi_vitis_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_vitis_control_BVALID : out STD_LOGIC;
    s_axi_vitis_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_vitis_control_RREADY : in STD_LOGIC;
    s_axi_vitis_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_vitis_control_RVALID : out STD_LOGIC;
    s_axi_vitis_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_vitis_control_WREADY : out STD_LOGIC;
    s_axi_vitis_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_vitis_control_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_gmem_invoer_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_invoer_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_invoer_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_invoer_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_invoer_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_invoer_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_invoer_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_invoer_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_invoer_ARREADY : in STD_LOGIC;
    m_axi_gmem_invoer_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_invoer_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_invoer_ARVALID : out STD_LOGIC;
    m_axi_gmem_invoer_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_invoer_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_invoer_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_invoer_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_invoer_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_invoer_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_invoer_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_invoer_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_invoer_AWREADY : in STD_LOGIC;
    m_axi_gmem_invoer_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_invoer_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_invoer_AWVALID : out STD_LOGIC;
    m_axi_gmem_invoer_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_invoer_BREADY : out STD_LOGIC;
    m_axi_gmem_invoer_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_invoer_BVALID : in STD_LOGIC;
    m_axi_gmem_invoer_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_invoer_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_invoer_RLAST : in STD_LOGIC;
    m_axi_gmem_invoer_RREADY : out STD_LOGIC;
    m_axi_gmem_invoer_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_invoer_RVALID : in STD_LOGIC;
    m_axi_gmem_invoer_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_invoer_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_invoer_WLAST : out STD_LOGIC;
    m_axi_gmem_invoer_WREADY : in STD_LOGIC;
    m_axi_gmem_invoer_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_invoer_WVALID : out STD_LOGIC;
    m_axi_gmem_uitvoer_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_uitvoer_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_uitvoer_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_uitvoer_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_uitvoer_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_uitvoer_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_uitvoer_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_uitvoer_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_uitvoer_ARREADY : in STD_LOGIC;
    m_axi_gmem_uitvoer_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_uitvoer_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_uitvoer_ARVALID : out STD_LOGIC;
    m_axi_gmem_uitvoer_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_gmem_uitvoer_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_uitvoer_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_uitvoer_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_uitvoer_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem_uitvoer_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_uitvoer_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_uitvoer_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_uitvoer_AWREADY : in STD_LOGIC;
    m_axi_gmem_uitvoer_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_uitvoer_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem_uitvoer_AWVALID : out STD_LOGIC;
    m_axi_gmem_uitvoer_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_uitvoer_BREADY : out STD_LOGIC;
    m_axi_gmem_uitvoer_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_uitvoer_BVALID : in STD_LOGIC;
    m_axi_gmem_uitvoer_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_uitvoer_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_uitvoer_RLAST : in STD_LOGIC;
    m_axi_gmem_uitvoer_RREADY : out STD_LOGIC;
    m_axi_gmem_uitvoer_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem_uitvoer_RVALID : in STD_LOGIC;
    m_axi_gmem_uitvoer_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem_uitvoer_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_gmem_uitvoer_WLAST : out STD_LOGIC;
    m_axi_gmem_uitvoer_WREADY : in STD_LOGIC;
    m_axi_gmem_uitvoer_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem_uitvoer_WVALID : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "design_1_filter_afbeelding_0_0,filter_afbeelding,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "design_1_filter_afbeelding_0_0,filter_afbeelding,{x_ipProduct=Vivado 2025.2,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=filter_afbeelding,x_ipVersion=1.0,x_ipCoreRevision=2114620840,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_VITIS_CONTROL_ADDR_WIDTH=6,C_S_AXI_VITIS_CONTROL_DATA_WIDTH=32,C_M_AXI_GMEM_INVOER_ID_WIDTH=1,C_M_AXI_GMEM_INVOER_ADDR_WIDTH=64,C_M_AXI_GMEM_INVOER_DATA_WIDTH=32,C_M_AXI_GMEM_INVOER_AWUSER_WIDTH=1,C_M_AXI_GMEM_INVOER_ARUSER_WIDTH=1,C_M_AXI_GMEM_INVOER_WUSER_WIDTH=1,C_M_AXI_GMEM_INVOER_RUSER_WIDTH=1,C_M_AXI_GMEM_INVOER_BUSER_WIDTH=1,C_M_AXI_GMEM_INVOER_USER_VALUE=0x00000000,C_M_AXI_GMEM_INVOER_PROT_VALUE=000,C_M_AXI_GMEM_INVOER_CACHE_VALUE=0011,C_M_AXI_GMEM_UITVOER_ID_WIDTH=1,C_M_AXI_GMEM_UITVOER_ADDR_WIDTH=64,C_M_AXI_GMEM_UITVOER_DATA_WIDTH=32,C_M_AXI_GMEM_UITVOER_AWUSER_WIDTH=1,C_M_AXI_GMEM_UITVOER_ARUSER_WIDTH=1,C_M_AXI_GMEM_UITVOER_WUSER_WIDTH=1,C_M_AXI_GMEM_UITVOER_RUSER_WIDTH=1,C_M_AXI_GMEM_UITVOER_BUSER_WIDTH=1,C_M_AXI_GMEM_UITVOER_USER_VALUE=0x00000000,C_M_AXI_GMEM_UITVOER_PROT_VALUE=000,C_M_AXI_GMEM_UITVOER_CACHE_VALUE=0011}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_vitis_control_ARADDR[5:0],s_axi_vitis_control_ARREADY,s_axi_vitis_control_ARVALID,s_axi_vitis_control_AWADDR[5:0],s_axi_vitis_control_AWREADY,s_axi_vitis_control_AWVALID,s_axi_vitis_control_BREADY,s_axi_vitis_control_BRESP[1:0],s_axi_vitis_control_BVALID,s_axi_vitis_control_RDATA[31:0],s_axi_vitis_control_RREADY,s_axi_vitis_control_RRESP[1:0],s_axi_vitis_control_RVALID,s_axi_vitis_control_WDATA[31:0],s_axi_vitis_control_WREADY,s_axi_vitis_control_WSTRB[3:0],s_axi_vitis_control_WVALID,ap_clk,ap_rst_n,interrupt,m_axi_gmem_invoer_ARADDR[63:0],m_axi_gmem_invoer_ARBURST[1:0],m_axi_gmem_invoer_ARCACHE[3:0],m_axi_gmem_invoer_ARID[0:0],m_axi_gmem_invoer_ARLEN[7:0],m_axi_gmem_invoer_ARLOCK[1:0],m_axi_gmem_invoer_ARPROT[2:0],m_axi_gmem_invoer_ARQOS[3:0],m_axi_gmem_invoer_ARREADY,m_axi_gmem_invoer_ARREGION[3:0],m_axi_gmem_invoer_ARSIZE[2:0],m_axi_gmem_invoer_ARVALID,m_axi_gmem_invoer_AWADDR[63:0],m_axi_gmem_invoer_AWBURST[1:0],m_axi_gmem_invoer_AWCACHE[3:0],m_axi_gmem_invoer_AWID[0:0],m_axi_gmem_invoer_AWLEN[7:0],m_axi_gmem_invoer_AWLOCK[1:0],m_axi_gmem_invoer_AWPROT[2:0],m_axi_gmem_invoer_AWQOS[3:0],m_axi_gmem_invoer_AWREADY,m_axi_gmem_invoer_AWREGION[3:0],m_axi_gmem_invoer_AWSIZE[2:0],m_axi_gmem_invoer_AWVALID,m_axi_gmem_invoer_BID[0:0],m_axi_gmem_invoer_BREADY,m_axi_gmem_invoer_BRESP[1:0],m_axi_gmem_invoer_BVALID,m_axi_gmem_invoer_RDATA[31:0],m_axi_gmem_invoer_RID[0:0],m_axi_gmem_invoer_RLAST,m_axi_gmem_invoer_RREADY,m_axi_gmem_invoer_RRESP[1:0],m_axi_gmem_invoer_RVALID,m_axi_gmem_invoer_WDATA[31:0],m_axi_gmem_invoer_WID[0:0],m_axi_gmem_invoer_WLAST,m_axi_gmem_invoer_WREADY,m_axi_gmem_invoer_WSTRB[3:0],m_axi_gmem_invoer_WVALID,m_axi_gmem_uitvoer_ARADDR[63:0],m_axi_gmem_uitvoer_ARBURST[1:0],m_axi_gmem_uitvoer_ARCACHE[3:0],m_axi_gmem_uitvoer_ARID[0:0],m_axi_gmem_uitvoer_ARLEN[7:0],m_axi_gmem_uitvoer_ARLOCK[1:0],m_axi_gmem_uitvoer_ARPROT[2:0],m_axi_gmem_uitvoer_ARQOS[3:0],m_axi_gmem_uitvoer_ARREADY,m_axi_gmem_uitvoer_ARREGION[3:0],m_axi_gmem_uitvoer_ARSIZE[2:0],m_axi_gmem_uitvoer_ARVALID,m_axi_gmem_uitvoer_AWADDR[63:0],m_axi_gmem_uitvoer_AWBURST[1:0],m_axi_gmem_uitvoer_AWCACHE[3:0],m_axi_gmem_uitvoer_AWID[0:0],m_axi_gmem_uitvoer_AWLEN[7:0],m_axi_gmem_uitvoer_AWLOCK[1:0],m_axi_gmem_uitvoer_AWPROT[2:0],m_axi_gmem_uitvoer_AWQOS[3:0],m_axi_gmem_uitvoer_AWREADY,m_axi_gmem_uitvoer_AWREGION[3:0],m_axi_gmem_uitvoer_AWSIZE[2:0],m_axi_gmem_uitvoer_AWVALID,m_axi_gmem_uitvoer_BID[0:0],m_axi_gmem_uitvoer_BREADY,m_axi_gmem_uitvoer_BRESP[1:0],m_axi_gmem_uitvoer_BVALID,m_axi_gmem_uitvoer_RDATA[31:0],m_axi_gmem_uitvoer_RID[0:0],m_axi_gmem_uitvoer_RLAST,m_axi_gmem_uitvoer_RREADY,m_axi_gmem_uitvoer_RRESP[1:0],m_axi_gmem_uitvoer_RVALID,m_axi_gmem_uitvoer_WDATA[31:0],m_axi_gmem_uitvoer_WID[0:0],m_axi_gmem_uitvoer_WLAST,m_axi_gmem_uitvoer_WREADY,m_axi_gmem_uitvoer_WSTRB[3:0],m_axi_gmem_uitvoer_WVALID";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_vitis_control_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_vitis_control_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_vitis_control_ARADDR : signal is "XIL_INTERFACENAME s_axi_vitis_control, ADDR_WIDTH 6, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control ARREADY";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control ARVALID";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control AWADDR";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control AWREADY";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control AWVALID";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control BREADY";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control BRESP";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control BVALID";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control RDATA";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control RREADY";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control RRESP";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control RVALID";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control WDATA";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control WREADY";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control WSTRB";
  attribute X_INTERFACE_INFO of s_axi_vitis_control_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_vitis_control WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_vitis_control:m_axi_gmem_invoer:m_axi_gmem_uitvoer, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem_invoer_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem_invoer_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem_invoer, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 64, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer BID";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer RID";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer WID";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem_invoer_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_invoer WVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer ARADDR";
  attribute X_INTERFACE_MODE of m_axi_gmem_uitvoer_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_gmem_uitvoer_ARADDR : signal is "XIL_INTERFACENAME m_axi_gmem_uitvoer, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 64, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer ARBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer ARID";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer ARLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer ARPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer ARQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer ARREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer ARREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer ARVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer AWADDR";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer AWBURST";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer AWID";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer AWLEN";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer AWPROT";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer AWQOS";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer AWREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer AWREGION";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer AWVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer BID";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer BREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer BRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer BVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer RDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer RID";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer RLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer RREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer RRESP";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer RVALID";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer WDATA";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer WID";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer WLAST";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer WREADY";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer WSTRB";
  attribute X_INTERFACE_INFO of m_axi_gmem_uitvoer_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_gmem_uitvoer WVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "filter_afbeelding,Vivado 2025.2";
begin
end;
